/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from './login';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from 'ionic-angular/util/events';
import * as import9 from 'ionic-angular/navigation/nav-controller';
import * as import10 from 'ionic-angular/navigation/nav-params';
import * as import11 from '@angular/core/src/metadata/view';
import * as import12 from '@angular/core/src/linker/component_factory';
import * as import13 from '../../node_modules/ionic-angular/components/toolbar/toolbar.ngfactory';
import * as import14 from '../../node_modules/ionic-angular/components/navbar/navbar.ngfactory';
import * as import15 from '../../node_modules/ionic-angular/components/button/button.ngfactory';
import * as import16 from '../../node_modules/ionic-angular/components/menu/menu-toggle.ngfactory';
import * as import17 from '../../node_modules/ionic-angular/components/toolbar/toolbar-item.ngfactory';
import * as import18 from '@angular/core/src/linker/query_list';
import * as import19 from '../../node_modules/ionic-angular/components/icon/icon.ngfactory';
import * as import20 from '../../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import21 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import22 from '../../node_modules/ionic-angular/components/card/card.ngfactory';
import * as import23 from '../../node_modules/ionic-angular/components/list/list.ngfactory';
import * as import24 from '../../node_modules/ionic-angular/components/item/item.ngfactory';
import * as import25 from 'ionic-angular/config/config';
import * as import26 from '@angular/core/src/linker/element_ref';
import * as import27 from 'ionic-angular/navigation/view-controller';
import * as import28 from 'ionic-angular/components/app/app';
import * as import29 from 'ionic-angular/components/menu/menu-controller';
import * as import30 from 'ionic-angular/components/toolbar/toolbar';
import * as import31 from 'ionic-angular/util/keyboard';
import * as import32 from '@angular/core/src/zone/ng_zone';
import * as import33 from 'ionic-angular/components/tabs/tabs';
import * as import34 from 'ionic-angular/gestures/gesture-controller';
import * as import35 from 'ionic-angular/util/form';
import * as import36 from 'ionic-angular/components/item/item-reorder';
import * as import37 from 'ionic-angular/components/icon/icon';
import * as import38 from 'ionic-angular/components/button/button';
import * as import39 from 'ionic-angular/components/menu/menu-toggle';
import * as import40 from 'ionic-angular/components/toolbar/toolbar-item';
import * as import41 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import42 from 'ionic-angular/components/navbar/navbar';
import * as import43 from 'ionic-angular/components/card/card';
import * as import44 from 'ionic-angular/components/item/item';
import * as import45 from 'ionic-angular/components/list/list';
import * as import46 from 'ionic-angular/components/content/content';
export class Wrapper_Login {
  context:import0.Login;
  changed:boolean;
  constructor(p0:any,p1:any,p2:any) {
    this.changed = false;
    this.context = new import0.Login(p0,p1,p2);
  }
  detectChangesInternal(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
}
var renderType_Login_Host:import2.RenderComponentType = (null as any);
class _View_Login_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _Login_0_4:Wrapper_Login;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_Login_Host0,renderType_Login_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.selectOrCreateHostElement('page-login',rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_Login0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Login_0_4 = new Wrapper_Login(this.parentInjector.get(import8.Events),this.parentInjector.get(import9.NavController),this.parentInjector.get(import10.NavParams));
    this._appEl_0.initComponent(this._Login_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._Login_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.Login) && (0 === requestNodeIndex))) { return this._Login_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._Login_0_4.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_Login_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_Login_Host === (null as any))) { (renderType_Login_Host = viewUtils.createRenderComponentType('',0,import11.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_Login_Host0(viewUtils,parentInjector,declarationEl);
}
export const LoginNgFactory:import12.ComponentFactory<import0.Login> = new import12.ComponentFactory<import0.Login>('page-login',viewFactory_Login_Host0,import0.Login);
const styles_Login:any[] = ([] as any[]);
var renderType_Login:import2.RenderComponentType = (null as any);
class _View_Login0 extends import1.AppView<import0.Login> {
  _el_0:any;
  _Header_0_3:import13.Wrapper_Header;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import3.AppElement;
  _Navbar_2_4:import14.Wrapper_Navbar;
  _text_3:any;
  _el_4:any;
  /*private*/ _appEl_4:import3.AppElement;
  _Button_4_4:import15.Wrapper_Button;
  _MenuToggle_4_5:import16.Wrapper_MenuToggle;
  _ToolbarItem_4_6:import17.Wrapper_ToolbarItem;
  _query_Button_4_0:import18.QueryList<any>;
  _text_5:any;
  _el_6:any;
  _Icon_6_3:import19.Wrapper_Icon;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  /*private*/ _appEl_9:import3.AppElement;
  _ToolbarTitle_9_4:import20.Wrapper_ToolbarTitle;
  _text_10:any;
  _text_11:any;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  /*private*/ _appEl_14:import3.AppElement;
  _Content_14_4:import21.Wrapper_Content;
  _text_15:any;
  _el_16:any;
  _Card_16_3:import22.Wrapper_Card;
  _text_17:any;
  _el_18:any;
  _CardHeader_18_3:import22.Wrapper_CardHeader;
  _text_19:any;
  _text_20:any;
  _el_21:any;
  _List_21_3:import23.Wrapper_List;
  _text_22:any;
  _el_23:any;
  /*private*/ _appEl_23:import3.AppElement;
  _Item_23_4:import24.Wrapper_Item;
  _ItemContent_23_5:import24.Wrapper_ItemContent;
  _query_Label_23_0:import18.QueryList<any>;
  _query_Button_23_1:import18.QueryList<any>;
  _query_Icon_23_2:import18.QueryList<any>;
  _text_24:any;
  _el_25:any;
  _Icon_25_3:import19.Wrapper_Icon;
  _text_26:any;
  _el_27:any;
  _text_28:any;
  _text_29:any;
  _text_30:any;
  _el_31:any;
  /*private*/ _appEl_31:import3.AppElement;
  _Item_31_4:import24.Wrapper_Item;
  _ItemContent_31_5:import24.Wrapper_ItemContent;
  _query_Label_31_0:import18.QueryList<any>;
  _query_Button_31_1:import18.QueryList<any>;
  _query_Icon_31_2:import18.QueryList<any>;
  _text_32:any;
  _el_33:any;
  _Icon_33_3:import19.Wrapper_Icon;
  _text_34:any;
  _el_35:any;
  _text_36:any;
  _text_37:any;
  _text_38:any;
  _el_39:any;
  /*private*/ _appEl_39:import3.AppElement;
  _Item_39_4:import24.Wrapper_Item;
  _ItemContent_39_5:import24.Wrapper_ItemContent;
  _query_Label_39_0:import18.QueryList<any>;
  _query_Button_39_1:import18.QueryList<any>;
  _query_Icon_39_2:import18.QueryList<any>;
  _text_40:any;
  _el_41:any;
  _Icon_41_3:import19.Wrapper_Icon;
  _text_42:any;
  _el_43:any;
  _text_44:any;
  _text_45:any;
  _text_46:any;
  _text_47:any;
  _text_48:any;
  _text_49:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_13:any;
  /*private*/ _expr_16:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_Login0,renderType_Login,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this._Header_0_3 = new import13.Wrapper_Header(this.parentInjector.get(import25.Config),new import26.ElementRef(this._el_0),this.renderer,this.parentInjector.get(import27.ViewController,(null as any)));
    this._text_1 = this.renderer.createText(this._el_0,'\n	',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-navbar',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','toolbar');
    this._appEl_2 = new import3.AppElement(2,0,this,this._el_2);
    var compView_2:any = import14.viewFactory_Navbar0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Navbar_2_4 = new import14.Wrapper_Navbar(this.parentInjector.get(import28.App),this.parentInjector.get(import27.ViewController,(null as any)),this.parentInjector.get(import9.NavController,(null as any)),this.parentInjector.get(import25.Config),new import26.ElementRef(this._el_2),this.renderer);
    this._appEl_2.initComponent(this._Navbar_2_4.context,([] as any[]),compView_2);
    this._text_3 = this.renderer.createText((null as any),'\n		',(null as any));
    this._el_4 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_4,'ion-button','');
    this.renderer.setElementAttribute(this._el_4,'menuToggle','');
    this._appEl_4 = new import3.AppElement(4,2,this,this._el_4);
    var compView_4:any = import15.viewFactory_Button0(this.viewUtils,this.injector(4),this._appEl_4);
    this._Button_4_4 = new import15.Wrapper_Button('','',this.parentInjector.get(import25.Config),new import26.ElementRef(this._el_4),this.renderer);
    this._MenuToggle_4_5 = new import16.Wrapper_MenuToggle(this.parentInjector.get(import29.MenuController),new import26.ElementRef(this._el_4),this.parentInjector.get(import27.ViewController,(null as any)),this._Navbar_2_4.context);
    this._ToolbarItem_4_6 = new import17.Wrapper_ToolbarItem(this.parentInjector.get(import25.Config),new import26.ElementRef(this._el_4),this.renderer,this.parentInjector.get(import30.Toolbar,(null as any)),this._Navbar_2_4.context);
    this._query_Button_4_0 = new import18.QueryList<any>();
    this._appEl_4.initComponent(this._Button_4_4.context,([] as any[]),compView_4);
    this._text_5 = this.renderer.createText((null as any),'\n			',(null as any));
    this._el_6 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_6,'name','menu');
    this.renderer.setElementAttribute(this._el_6,'role','img');
    this._Icon_6_3 = new import19.Wrapper_Icon(this.parentInjector.get(import25.Config),new import26.ElementRef(this._el_6),this.renderer);
    this._text_7 = this.renderer.createText((null as any),'\n		',(null as any));
      compView_4.create(this._Button_4_4.context,[([] as any[]).concat([
        this._text_5,
        this._el_6,
        this._text_7
      ]
    )],(null as any));
    this._text_8 = this.renderer.createText((null as any),'\n		',(null as any));
    this._el_9 = this.renderer.createElement((null as any),'ion-title',(null as any));
    this._appEl_9 = new import3.AppElement(9,2,this,this._el_9);
    var compView_9:any = import20.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(9),this._appEl_9);
    this._ToolbarTitle_9_4 = new import20.Wrapper_ToolbarTitle(this.parentInjector.get(import25.Config),new import26.ElementRef(this._el_9),this.renderer,this.parentInjector.get(import30.Toolbar,(null as any)),this._Navbar_2_4.context);
    this._appEl_9.initComponent(this._ToolbarTitle_9_4.context,([] as any[]),compView_9);
    this._text_10 = this.renderer.createText((null as any),'Login',(null as any));
    compView_9.create(this._ToolbarTitle_9_4.context,[([] as any[]).concat([this._text_10])],(null as any));
    this._text_11 = this.renderer.createText((null as any),'\n	',(null as any));
    compView_2.create(this._Navbar_2_4.context,[
      ([] as any[]).concat([this._el_4]),
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_3,
        this._text_8,
        this._el_9,
        this._text_11
      ]
      )
    ]
    ,(null as any));
    this._text_12 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_13 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_14 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this._appEl_14 = new import3.AppElement(14,(null as any),this,this._el_14);
    var compView_14:any = import21.viewFactory_Content0(this.viewUtils,this.injector(14),this._appEl_14);
    this._Content_14_4 = new import21.Wrapper_Content(this.parentInjector.get(import25.Config),new import26.ElementRef(this._el_14),this.renderer,this.parentInjector.get(import28.App),this.parentInjector.get(import31.Keyboard),this.parentInjector.get(import32.NgZone),this.parentInjector.get(import27.ViewController,(null as any)),this.parentInjector.get(import33.Tabs,(null as any)));
    this._appEl_14.initComponent(this._Content_14_4.context,([] as any[]),compView_14);
    this._text_15 = this.renderer.createText((null as any),'\n\n	',(null as any));
    this._el_16 = this.renderer.createElement((null as any),'ion-card',(null as any));
    this._Card_16_3 = new import22.Wrapper_Card(this.parentInjector.get(import25.Config),new import26.ElementRef(this._el_16),this.renderer);
    this._text_17 = this.renderer.createText(this._el_16,'\n\n		',(null as any));
    this._el_18 = this.renderer.createElement(this._el_16,'ion-card-header',(null as any));
    this._CardHeader_18_3 = new import22.Wrapper_CardHeader(this.parentInjector.get(import25.Config),new import26.ElementRef(this._el_18),this.renderer);
    this._text_19 = this.renderer.createText(this._el_18,'\n			Login with\n		',(null as any));
    this._text_20 = this.renderer.createText(this._el_16,'\n\n		',(null as any));
    this._el_21 = this.renderer.createElement(this._el_16,'ion-list',(null as any));
    this._List_21_3 = new import23.Wrapper_List(this.parentInjector.get(import25.Config),new import26.ElementRef(this._el_21),this.renderer,this.parentInjector.get(import34.GestureController));
    this._text_22 = this.renderer.createText(this._el_21,'\n\n			',(null as any));
    this._el_23 = this.renderer.createElement(this._el_21,'button',(null as any));
    this.renderer.setElementAttribute(this._el_23,'class','item item-block');
    this.renderer.setElementAttribute(this._el_23,'ion-item','');
    this._appEl_23 = new import3.AppElement(23,21,this,this._el_23);
    var compView_23:any = import24.viewFactory_Item0(this.viewUtils,this.injector(23),this._appEl_23);
    this._Item_23_4 = new import24.Wrapper_Item(this.parentInjector.get(import35.Form),this.parentInjector.get(import25.Config),new import26.ElementRef(this._el_23),this.renderer,this.parentInjector.get(import36.ItemReorder,(null as any)));
    this._ItemContent_23_5 = new import24.Wrapper_ItemContent();
    this._query_Label_23_0 = new import18.QueryList<any>();
    this._query_Button_23_1 = new import18.QueryList<any>();
    this._query_Icon_23_2 = new import18.QueryList<any>();
    this._appEl_23.initComponent(this._Item_23_4.context,([] as any[]),compView_23);
    this._text_24 = this.renderer.createText((null as any),'\n				',(null as any));
    this._el_25 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_25,'class','login-social-icon facebook');
    this.renderer.setElementAttribute(this._el_25,'item-left','');
    this.renderer.setElementAttribute(this._el_25,'name','logo-facebook');
    this.renderer.setElementAttribute(this._el_25,'role','img');
    this._Icon_25_3 = new import19.Wrapper_Icon(this.parentInjector.get(import25.Config),new import26.ElementRef(this._el_25),this.renderer);
    this._text_26 = this.renderer.createText((null as any),'\n				',(null as any));
    this._el_27 = this.renderer.createElement((null as any),'h3',(null as any));
    this.renderer.setElementAttribute(this._el_27,'class','login-social-name');
    this._text_28 = this.renderer.createText(this._el_27,'Facebook',(null as any));
    this._text_29 = this.renderer.createText((null as any),'\n			',(null as any));
    this._query_Label_23_0.reset(([] as any[]));
    this._Item_23_4.context.contentLabel = this._query_Label_23_0.first;
    compView_23.create(this._Item_23_4.context,[
      ([] as any[]).concat([this._el_25]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_24,
        this._text_26,
        this._el_27,
        this._text_29
      ]
      ),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_30 = this.renderer.createText(this._el_21,'\n\n			',(null as any));
    this._el_31 = this.renderer.createElement(this._el_21,'button',(null as any));
    this.renderer.setElementAttribute(this._el_31,'class','item item-block');
    this.renderer.setElementAttribute(this._el_31,'ion-item','');
    this._appEl_31 = new import3.AppElement(31,21,this,this._el_31);
    var compView_31:any = import24.viewFactory_Item0(this.viewUtils,this.injector(31),this._appEl_31);
    this._Item_31_4 = new import24.Wrapper_Item(this.parentInjector.get(import35.Form),this.parentInjector.get(import25.Config),new import26.ElementRef(this._el_31),this.renderer,this.parentInjector.get(import36.ItemReorder,(null as any)));
    this._ItemContent_31_5 = new import24.Wrapper_ItemContent();
    this._query_Label_31_0 = new import18.QueryList<any>();
    this._query_Button_31_1 = new import18.QueryList<any>();
    this._query_Icon_31_2 = new import18.QueryList<any>();
    this._appEl_31.initComponent(this._Item_31_4.context,([] as any[]),compView_31);
    this._text_32 = this.renderer.createText((null as any),'\n				',(null as any));
    this._el_33 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_33,'class','login-social-icon google');
    this.renderer.setElementAttribute(this._el_33,'item-left','');
    this.renderer.setElementAttribute(this._el_33,'name','logo-google');
    this.renderer.setElementAttribute(this._el_33,'role','img');
    this._Icon_33_3 = new import19.Wrapper_Icon(this.parentInjector.get(import25.Config),new import26.ElementRef(this._el_33),this.renderer);
    this._text_34 = this.renderer.createText((null as any),'\n				',(null as any));
    this._el_35 = this.renderer.createElement((null as any),'h3',(null as any));
    this.renderer.setElementAttribute(this._el_35,'class','login-social-name');
    this._text_36 = this.renderer.createText(this._el_35,'Google',(null as any));
    this._text_37 = this.renderer.createText((null as any),'\n			',(null as any));
    this._query_Label_31_0.reset(([] as any[]));
    this._Item_31_4.context.contentLabel = this._query_Label_31_0.first;
    compView_31.create(this._Item_31_4.context,[
      ([] as any[]).concat([this._el_33]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_32,
        this._text_34,
        this._el_35,
        this._text_37
      ]
      ),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_38 = this.renderer.createText(this._el_21,'\n\n			',(null as any));
    this._el_39 = this.renderer.createElement(this._el_21,'button',(null as any));
    this.renderer.setElementAttribute(this._el_39,'class','item item-block');
    this.renderer.setElementAttribute(this._el_39,'ion-item','');
    this._appEl_39 = new import3.AppElement(39,21,this,this._el_39);
    var compView_39:any = import24.viewFactory_Item0(this.viewUtils,this.injector(39),this._appEl_39);
    this._Item_39_4 = new import24.Wrapper_Item(this.parentInjector.get(import35.Form),this.parentInjector.get(import25.Config),new import26.ElementRef(this._el_39),this.renderer,this.parentInjector.get(import36.ItemReorder,(null as any)));
    this._ItemContent_39_5 = new import24.Wrapper_ItemContent();
    this._query_Label_39_0 = new import18.QueryList<any>();
    this._query_Button_39_1 = new import18.QueryList<any>();
    this._query_Icon_39_2 = new import18.QueryList<any>();
    this._appEl_39.initComponent(this._Item_39_4.context,([] as any[]),compView_39);
    this._text_40 = this.renderer.createText((null as any),'\n				',(null as any));
    this._el_41 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_41,'class','login-social-icon twitter');
    this.renderer.setElementAttribute(this._el_41,'item-left','');
    this.renderer.setElementAttribute(this._el_41,'name','logo-twitter');
    this.renderer.setElementAttribute(this._el_41,'role','img');
    this._Icon_41_3 = new import19.Wrapper_Icon(this.parentInjector.get(import25.Config),new import26.ElementRef(this._el_41),this.renderer);
    this._text_42 = this.renderer.createText((null as any),'\n				',(null as any));
    this._el_43 = this.renderer.createElement((null as any),'h3',(null as any));
    this.renderer.setElementAttribute(this._el_43,'class','login-social-name');
    this._text_44 = this.renderer.createText(this._el_43,'Twitter',(null as any));
    this._text_45 = this.renderer.createText((null as any),'\n			',(null as any));
    this._query_Label_39_0.reset(([] as any[]));
    this._Item_39_4.context.contentLabel = this._query_Label_39_0.first;
    compView_39.create(this._Item_39_4.context,[
      ([] as any[]).concat([this._el_41]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_40,
        this._text_42,
        this._el_43,
        this._text_45
      ]
      ),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_46 = this.renderer.createText(this._el_21,'\n\n		',(null as any));
    this._text_47 = this.renderer.createText(this._el_16,'\n\n	',(null as any));
    this._text_48 = this.renderer.createText((null as any),'\n',(null as any));
    compView_14.create(this._Content_14_4.context,[
      ([] as any[]),
      ([] as any[]).concat([
        this._text_15,
        this._el_16,
        this._text_48
      ]
      ),
      ([] as any[])
    ]
    ,(null as any));
    this._text_49 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_4,'click',this.eventHandler(this._handle_click_4_0.bind(this)));
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    var disposable_1:Function = this.renderer.listen(this._el_23,'click',this.eventHandler(this._handle_click_23_0.bind(this)));
    this._expr_10 = import7.UNINITIALIZED;
    var disposable_2:Function = this.renderer.listen(this._el_31,'click',this.eventHandler(this._handle_click_31_0.bind(this)));
    this._expr_13 = import7.UNINITIALIZED;
    var disposable_3:Function = this.renderer.listen(this._el_39,'click',this.eventHandler(this._handle_click_39_0.bind(this)));
    this._expr_16 = import7.UNINITIALIZED;
    this.init(([] as any[]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._el_27,
      this._text_28,
      this._text_29,
      this._text_30,
      this._el_31,
      this._text_32,
      this._el_33,
      this._text_34,
      this._el_35,
      this._text_36,
      this._text_37,
      this._text_38,
      this._el_39,
      this._text_40,
      this._el_41,
      this._text_42,
      this._el_43,
      this._text_44,
      this._text_45,
      this._text_46,
      this._text_47,
      this._text_48,
      this._text_49
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3
    ]
    ,([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import37.Icon) && (6 === requestNodeIndex))) { return this._Icon_6_3.context; }
    if (((token === import38.Button) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._Button_4_4.context; }
    if (((token === import39.MenuToggle) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._MenuToggle_4_5.context; }
    if (((token === import40.ToolbarItem) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._ToolbarItem_4_6.context; }
    if (((token === import41.ToolbarTitle) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 10)))) { return this._ToolbarTitle_9_4.context; }
    if (((token === import42.Navbar) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 11)))) { return this._Navbar_2_4.context; }
    if (((token === import30.Header) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 12)))) { return this._Header_0_3.context; }
    if (((token === import43.CardHeader) && ((18 <= requestNodeIndex) && (requestNodeIndex <= 19)))) { return this._CardHeader_18_3.context; }
    if (((token === import37.Icon) && (25 === requestNodeIndex))) { return this._Icon_25_3.context; }
    if (((token === import44.Item) && ((23 <= requestNodeIndex) && (requestNodeIndex <= 29)))) { return this._Item_23_4.context; }
    if (((token === import44.ItemContent) && ((23 <= requestNodeIndex) && (requestNodeIndex <= 29)))) { return this._ItemContent_23_5.context; }
    if (((token === import37.Icon) && (33 === requestNodeIndex))) { return this._Icon_33_3.context; }
    if (((token === import44.Item) && ((31 <= requestNodeIndex) && (requestNodeIndex <= 37)))) { return this._Item_31_4.context; }
    if (((token === import44.ItemContent) && ((31 <= requestNodeIndex) && (requestNodeIndex <= 37)))) { return this._ItemContent_31_5.context; }
    if (((token === import37.Icon) && (41 === requestNodeIndex))) { return this._Icon_41_3.context; }
    if (((token === import44.Item) && ((39 <= requestNodeIndex) && (requestNodeIndex <= 45)))) { return this._Item_39_4.context; }
    if (((token === import44.ItemContent) && ((39 <= requestNodeIndex) && (requestNodeIndex <= 45)))) { return this._ItemContent_39_5.context; }
    if (((token === import45.List) && ((21 <= requestNodeIndex) && (requestNodeIndex <= 46)))) { return this._List_21_3.context; }
    if (((token === import43.Card) && ((16 <= requestNodeIndex) && (requestNodeIndex <= 47)))) { return this._Card_16_3.context; }
    if (((token === import46.Content) && ((14 <= requestNodeIndex) && (requestNodeIndex <= 48)))) { return this._Content_14_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._Header_0_3.detectChangesInternal(this,this._el_0,throwOnChange);
    this._Navbar_2_4.detectChangesInternal(this,this._el_2,throwOnChange);
    if (this._Button_4_4.detectChangesInternal(this,this._el_4,throwOnChange)) { this._appEl_4.componentView.markAsCheckOnce(); }
    const currVal_3:any = '';
    this._MenuToggle_4_5.check_menuToggle(currVal_3,throwOnChange,false);
    this._MenuToggle_4_5.detectChangesInternal(this,this._el_4,throwOnChange);
    this._ToolbarItem_4_6.detectChangesInternal(this,this._el_4,throwOnChange);
    const currVal_5:any = 'menu';
    this._Icon_6_3.check_name(currVal_5,throwOnChange,false);
    this._Icon_6_3.detectChangesInternal(this,this._el_6,throwOnChange);
    if (this._ToolbarTitle_9_4.detectChangesInternal(this,this._el_9,throwOnChange)) { this._appEl_9.componentView.markAsCheckOnce(); }
    if (this._Content_14_4.detectChangesInternal(this,this._el_14,throwOnChange)) { this._appEl_14.componentView.markAsCheckOnce(); }
    this._Card_16_3.detectChangesInternal(this,this._el_16,throwOnChange);
    this._CardHeader_18_3.detectChangesInternal(this,this._el_18,throwOnChange);
    this._List_21_3.detectChangesInternal(this,this._el_21,throwOnChange);
    if (this._Item_23_4.detectChangesInternal(this,this._el_23,throwOnChange)) { this._appEl_23.componentView.markAsCheckOnce(); }
    this._ItemContent_23_5.detectChangesInternal(this,this._el_23,throwOnChange);
    const currVal_9:any = 'logo-facebook';
    this._Icon_25_3.check_name(currVal_9,throwOnChange,false);
    this._Icon_25_3.detectChangesInternal(this,this._el_25,throwOnChange);
    if (this._Item_31_4.detectChangesInternal(this,this._el_31,throwOnChange)) { this._appEl_31.componentView.markAsCheckOnce(); }
    this._ItemContent_31_5.detectChangesInternal(this,this._el_31,throwOnChange);
    const currVal_12:any = 'logo-google';
    this._Icon_33_3.check_name(currVal_12,throwOnChange,false);
    this._Icon_33_3.detectChangesInternal(this,this._el_33,throwOnChange);
    if (this._Item_39_4.detectChangesInternal(this,this._el_39,throwOnChange)) { this._appEl_39.componentView.markAsCheckOnce(); }
    this._ItemContent_39_5.detectChangesInternal(this,this._el_39,throwOnChange);
    const currVal_15:any = 'logo-twitter';
    this._Icon_41_3.check_name(currVal_15,throwOnChange,false);
    this._Icon_41_3.detectChangesInternal(this,this._el_41,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_4_0.dirty) {
        this._query_Button_4_0.reset([this._Button_4_4.context]);
        this._ToolbarItem_4_6.context._buttons = this._query_Button_4_0;
        this._query_Button_4_0.notifyOnChanges();
      }
      if (this._query_Button_23_1.dirty) {
        this._query_Button_23_1.reset(([] as any[]));
        this._Item_23_4.context._buttons = this._query_Button_23_1;
        this._query_Button_23_1.notifyOnChanges();
      }
      if (this._query_Icon_23_2.dirty) {
        this._query_Icon_23_2.reset([this._Icon_25_3.context]);
        this._Item_23_4.context._icons = this._query_Icon_23_2;
        this._query_Icon_23_2.notifyOnChanges();
      }
      if (this._query_Button_31_1.dirty) {
        this._query_Button_31_1.reset(([] as any[]));
        this._Item_31_4.context._buttons = this._query_Button_31_1;
        this._query_Button_31_1.notifyOnChanges();
      }
      if (this._query_Icon_31_2.dirty) {
        this._query_Icon_31_2.reset([this._Icon_33_3.context]);
        this._Item_31_4.context._icons = this._query_Icon_31_2;
        this._query_Icon_31_2.notifyOnChanges();
      }
      if (this._query_Button_39_1.dirty) {
        this._query_Button_39_1.reset(([] as any[]));
        this._Item_39_4.context._buttons = this._query_Button_39_1;
        this._query_Button_39_1.notifyOnChanges();
      }
      if (this._query_Icon_39_2.dirty) {
        this._query_Icon_39_2.reset([this._Icon_41_3.context]);
        this._Item_39_4.context._icons = this._query_Icon_39_2;
        this._query_Icon_39_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Button_4_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_23_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_31_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_39_4.context.ngAfterContentInit(); }
    }
    const currVal_0:any = this._Navbar_2_4.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_2,'hidden',currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = this._Navbar_2_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementClass(this._el_2,'statusbar-padding',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_4:any = this._MenuToggle_4_5.context.isHidden;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementProperty(this._el_4,'hidden',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_6:any = this._Icon_6_3.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementClass(this._el_6,'hide',currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = this._Content_14_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_14,'statusbar-padding',currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_10:any = this._Icon_25_3.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this.renderer.setElementClass(this._el_25,'hide',currVal_10);
      this._expr_10 = currVal_10;
    }
    const currVal_13:any = this._Icon_33_3.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this.renderer.setElementClass(this._el_33,'hide',currVal_13);
      this._expr_13 = currVal_13;
    }
    const currVal_16:any = this._Icon_41_3.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_16,currVal_16)) {
      this.renderer.setElementClass(this._el_41,'hide',currVal_16);
      this._expr_16 = currVal_16;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Navbar_2_4.context.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._Icon_6_3.context.ngOnDestroy();
    this._Icon_25_3.context.ngOnDestroy();
    this._Icon_33_3.context.ngOnDestroy();
    this._Icon_41_3.context.ngOnDestroy();
    this._Content_14_4.context.ngOnDestroy();
  }
  private _handle_click_4_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._MenuToggle_4_5.context.toggle()) !== false);
    return (true && pd_0);
  }
  private _handle_click_23_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.socialLogin('facebook')) !== false);
    return (true && pd_0);
  }
  private _handle_click_31_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.socialLogin('google')) !== false);
    return (true && pd_0);
  }
  private _handle_click_39_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.socialLogin('twitter')) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_Login0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.Login> {
  if ((renderType_Login === (null as any))) { (renderType_Login = viewUtils.createRenderComponentType('',0,import11.ViewEncapsulation.None,styles_Login,{})); }
  return new _View_Login0(viewUtils,parentInjector,declarationEl);
}