/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from './invite';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from 'ionic-angular/navigation/nav-controller';
import * as import9 from '@angular/core/src/metadata/view';
import * as import10 from '@angular/core/src/linker/component_factory';
import * as import11 from '../../node_modules/ionic-angular/components/toolbar/toolbar.ngfactory';
import * as import12 from '../../node_modules/ionic-angular/components/navbar/navbar.ngfactory';
import * as import13 from '../../node_modules/ionic-angular/components/toolbar/toolbar-item.ngfactory';
import * as import14 from '@angular/core/src/linker/query_list';
import * as import15 from '../../node_modules/ionic-angular/components/button/button.ngfactory';
import * as import16 from '../../node_modules/ionic-angular/components/menu/menu-toggle.ngfactory';
import * as import17 from '../../node_modules/ionic-angular/components/icon/icon.ngfactory';
import * as import18 from '../../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import19 from '../../node_modules/ionic-angular/components/searchbar/searchbar.ngfactory';
import * as import20 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import21 from '../../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import22 from '../../node_modules/ionic-angular/components/list/list.ngfactory';
import * as import23 from '../../node_modules/@angular/common/src/directives/ng_for.ngfactory';
import * as import24 from '../../node_modules/ionic-angular/components/infinite-scroll/infinite-scroll.ngfactory';
import * as import25 from '../../node_modules/ionic-angular/components/infinite-scroll/infinite-scroll-content.ngfactory';
import * as import26 from 'ionic-angular/config/config';
import * as import27 from '@angular/core/src/linker/element_ref';
import * as import28 from 'ionic-angular/navigation/view-controller';
import * as import29 from 'ionic-angular/components/app/app';
import * as import30 from 'ionic-angular/components/toolbar/toolbar';
import * as import31 from 'ionic-angular/components/menu/menu-controller';
import * as import32 from '@angular/forms/src/directives/ng_control';
import * as import33 from 'ionic-angular/util/keyboard';
import * as import34 from '@angular/core/src/zone/ng_zone';
import * as import35 from 'ionic-angular/components/tabs/tabs';
import * as import36 from '@angular/core/src/linker/template_ref';
import * as import37 from 'ionic-angular/gestures/gesture-controller';
import * as import38 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import39 from 'ionic-angular/components/icon/icon';
import * as import40 from 'ionic-angular/components/button/button';
import * as import41 from 'ionic-angular/components/menu/menu-toggle';
import * as import42 from 'ionic-angular/components/toolbar/toolbar-item';
import * as import43 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import44 from 'ionic-angular/components/navbar/navbar';
import * as import45 from 'ionic-angular/components/searchbar/searchbar';
import * as import46 from '@angular/common/src/directives/ng_if';
import * as import47 from '@angular/common/src/directives/ng_for';
import * as import48 from 'ionic-angular/components/list/list';
import * as import49 from 'ionic-angular/components/infinite-scroll/infinite-scroll-content';
import * as import50 from 'ionic-angular/components/infinite-scroll/infinite-scroll';
import * as import51 from 'ionic-angular/components/content/content';
import * as import52 from '../../node_modules/ionic-angular/components/item/item.ngfactory';
import * as import53 from 'ionic-angular/util/form';
import * as import54 from 'ionic-angular/components/item/item-reorder';
import * as import55 from 'ionic-angular/components/item/item';
import * as import56 from '../../node_modules/ionic-angular/components/avatar/avatar.ngfactory';
import * as import57 from '../../node_modules/@angular/common/src/directives/ng_class.ngfactory';
import * as import58 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import59 from 'ionic-angular/components/avatar/avatar';
import * as import60 from '@angular/common/src/directives/ng_class';
import * as import61 from '@angular/core/src/security';
export class Wrapper_Invite {
  context:import0.Invite;
  changed:boolean;
  constructor(p0:any,p1:any) {
    this.changed = false;
    this.context = new import0.Invite(p0,p1);
  }
  detectChangesInternal(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
}
var renderType_Invite_Host:import2.RenderComponentType = (null as any);
class _View_Invite_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _Invite_0_4:Wrapper_Invite;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_Invite_Host0,renderType_Invite_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.selectOrCreateHostElement('page-invite',rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_Invite0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Invite_0_4 = new Wrapper_Invite(this.parentInjector.get(import8.NavController),compView_0.ref);
    this._appEl_0.initComponent(this._Invite_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._Invite_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.Invite) && (0 === requestNodeIndex))) { return this._Invite_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._Invite_0_4.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_Invite_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_Invite_Host === (null as any))) { (renderType_Invite_Host = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_Invite_Host0(viewUtils,parentInjector,declarationEl);
}
export const InviteNgFactory:import10.ComponentFactory<import0.Invite> = new import10.ComponentFactory<import0.Invite>('page-invite',viewFactory_Invite_Host0,import0.Invite);
const styles_Invite:any[] = ([] as any[]);
var renderType_Invite:import2.RenderComponentType = (null as any);
class _View_Invite0 extends import1.AppView<import0.Invite> {
  _el_0:any;
  _Header_0_3:import11.Wrapper_Header;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import3.AppElement;
  _Navbar_2_4:import12.Wrapper_Navbar;
  _text_3:any;
  _el_4:any;
  _ToolbarItem_4_3:import13.Wrapper_ToolbarItem;
  _query_Button_4_0:import14.QueryList<any>;
  _text_5:any;
  _el_6:any;
  /*private*/ _appEl_6:import3.AppElement;
  _Button_6_4:import15.Wrapper_Button;
  _MenuToggle_6_5:import16.Wrapper_MenuToggle;
  _ToolbarItem_6_6:import13.Wrapper_ToolbarItem;
  _query_Button_6_0:import14.QueryList<any>;
  _text_7:any;
  _el_8:any;
  _Icon_8_3:import17.Wrapper_Icon;
  _text_9:any;
  _text_10:any;
  _text_11:any;
  _el_12:any;
  /*private*/ _appEl_12:import3.AppElement;
  _ToolbarTitle_12_4:import18.Wrapper_ToolbarTitle;
  _text_13:any;
  _text_14:any;
  _text_15:any;
  _el_16:any;
  /*private*/ _appEl_16:import3.AppElement;
  _Searchbar_16_4:import19.Wrapper_Searchbar;
  _text_17:any;
  _text_18:any;
  _el_19:any;
  /*private*/ _appEl_19:import3.AppElement;
  _Content_19_4:import20.Wrapper_Content;
  _text_20:any;
  _anchor_21:any;
  /*private*/ _appEl_21:import3.AppElement;
  _TemplateRef_21_5:any;
  _NgIf_21_6:import21.Wrapper_NgIf;
  _text_22:any;
  _el_23:any;
  _List_23_3:import22.Wrapper_List;
  _text_24:any;
  _anchor_25:any;
  /*private*/ _appEl_25:import3.AppElement;
  _TemplateRef_25_5:any;
  _NgFor_25_6:import23.Wrapper_NgFor;
  _text_26:any;
  _text_27:any;
  _anchor_28:any;
  /*private*/ _appEl_28:import3.AppElement;
  _TemplateRef_28_5:any;
  _NgIf_28_6:import21.Wrapper_NgIf;
  _text_29:any;
  _el_30:any;
  _InfiniteScroll_30_3:import24.Wrapper_InfiniteScroll;
  _text_31:any;
  _el_32:any;
  /*private*/ _appEl_32:import3.AppElement;
  _InfiniteScrollContent_32_4:import25.Wrapper_InfiniteScrollContent;
  _text_33:any;
  _text_34:any;
  _text_35:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_13:any;
  /*private*/ _expr_14:any;
  /*private*/ _expr_19:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_Invite0,renderType_Invite,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this._Header_0_3 = new import11.Wrapper_Header(this.parentInjector.get(import26.Config),new import27.ElementRef(this._el_0),this.renderer,this.parentInjector.get(import28.ViewController,(null as any)));
    this._text_1 = this.renderer.createText(this._el_0,'\n	',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-navbar',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','toolbar');
    this._appEl_2 = new import3.AppElement(2,0,this,this._el_2);
    var compView_2:any = import12.viewFactory_Navbar0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Navbar_2_4 = new import12.Wrapper_Navbar(this.parentInjector.get(import29.App),this.parentInjector.get(import28.ViewController,(null as any)),this.parentInjector.get(import8.NavController,(null as any)),this.parentInjector.get(import26.Config),new import27.ElementRef(this._el_2),this.renderer);
    this._appEl_2.initComponent(this._Navbar_2_4.context,([] as any[]),compView_2);
    this._text_3 = this.renderer.createText((null as any),'\n		',(null as any));
    this._el_4 = this.renderer.createElement((null as any),'ion-buttons',(null as any));
    this.renderer.setElementAttribute(this._el_4,'start','');
    this._ToolbarItem_4_3 = new import13.Wrapper_ToolbarItem(this.parentInjector.get(import26.Config),new import27.ElementRef(this._el_4),this.renderer,this.parentInjector.get(import30.Toolbar,(null as any)),this._Navbar_2_4.context);
    this._query_Button_4_0 = new import14.QueryList<any>();
    this._text_5 = this.renderer.createText(this._el_4,'\n			',(null as any));
    this._el_6 = this.renderer.createElement(this._el_4,'button',(null as any));
    this.renderer.setElementAttribute(this._el_6,'ion-button','');
    this.renderer.setElementAttribute(this._el_6,'menuToggle','');
    this._appEl_6 = new import3.AppElement(6,4,this,this._el_6);
    var compView_6:any = import15.viewFactory_Button0(this.viewUtils,this.injector(6),this._appEl_6);
    this._Button_6_4 = new import15.Wrapper_Button('','',this.parentInjector.get(import26.Config),new import27.ElementRef(this._el_6),this.renderer);
    this._MenuToggle_6_5 = new import16.Wrapper_MenuToggle(this.parentInjector.get(import31.MenuController),new import27.ElementRef(this._el_6),this.parentInjector.get(import28.ViewController,(null as any)),this._Navbar_2_4.context);
    this._ToolbarItem_6_6 = new import13.Wrapper_ToolbarItem(this.parentInjector.get(import26.Config),new import27.ElementRef(this._el_6),this.renderer,this.parentInjector.get(import30.Toolbar,(null as any)),this._Navbar_2_4.context);
    this._query_Button_6_0 = new import14.QueryList<any>();
    this._appEl_6.initComponent(this._Button_6_4.context,([] as any[]),compView_6);
    this._text_7 = this.renderer.createText((null as any),'\n				',(null as any));
    this._el_8 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_8,'name','menu');
    this.renderer.setElementAttribute(this._el_8,'role','img');
    this._Icon_8_3 = new import17.Wrapper_Icon(this.parentInjector.get(import26.Config),new import27.ElementRef(this._el_8),this.renderer);
    this._text_9 = this.renderer.createText((null as any),'\n			',(null as any));
      compView_6.create(this._Button_6_4.context,[([] as any[]).concat([
        this._text_7,
        this._el_8,
        this._text_9
      ]
    )],(null as any));
    this._text_10 = this.renderer.createText(this._el_4,'\n		',(null as any));
    this._text_11 = this.renderer.createText((null as any),'\n		',(null as any));
    this._el_12 = this.renderer.createElement((null as any),'ion-title',(null as any));
    this._appEl_12 = new import3.AppElement(12,2,this,this._el_12);
    var compView_12:any = import18.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(12),this._appEl_12);
    this._ToolbarTitle_12_4 = new import18.Wrapper_ToolbarTitle(this.parentInjector.get(import26.Config),new import27.ElementRef(this._el_12),this.renderer,this.parentInjector.get(import30.Toolbar,(null as any)),this._Navbar_2_4.context);
    this._appEl_12.initComponent(this._ToolbarTitle_12_4.context,([] as any[]),compView_12);
    this._text_13 = this.renderer.createText((null as any),'Invite',(null as any));
    compView_12.create(this._ToolbarTitle_12_4.context,[([] as any[]).concat([this._text_13])],(null as any));
    this._text_14 = this.renderer.createText((null as any),'\n	',(null as any));
    compView_2.create(this._Navbar_2_4.context,[
      ([] as any[]),
      ([] as any[]).concat([this._el_4]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_3,
        this._text_11,
        this._el_12,
        this._text_14
      ]
      )
    ]
    ,(null as any));
    this._text_15 = this.renderer.createText(this._el_0,'\n	',(null as any));
    this._el_16 = this.renderer.createElement(this._el_0,'ion-searchbar',(null as any));
    this._appEl_16 = new import3.AppElement(16,0,this,this._el_16);
    var compView_16:any = import19.viewFactory_Searchbar0(this.viewUtils,this.injector(16),this._appEl_16);
    this._Searchbar_16_4 = new import19.Wrapper_Searchbar(this.parentInjector.get(import26.Config),new import27.ElementRef(this._el_16),this.renderer,this.parentInjector.get(import32.NgControl,(null as any)));
    this._appEl_16.initComponent(this._Searchbar_16_4.context,([] as any[]),compView_16);
    compView_16.create(this._Searchbar_16_4.context,([] as any[]),(null as any));
    this._text_17 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_18 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_19 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this._appEl_19 = new import3.AppElement(19,(null as any),this,this._el_19);
    var compView_19:any = import20.viewFactory_Content0(this.viewUtils,this.injector(19),this._appEl_19);
    this._Content_19_4 = new import20.Wrapper_Content(this.parentInjector.get(import26.Config),new import27.ElementRef(this._el_19),this.renderer,this.parentInjector.get(import29.App),this.parentInjector.get(import33.Keyboard),this.parentInjector.get(import34.NgZone),this.parentInjector.get(import28.ViewController,(null as any)),this.parentInjector.get(import35.Tabs,(null as any)));
    this._appEl_19.initComponent(this._Content_19_4.context,([] as any[]),compView_19);
    this._text_20 = this.renderer.createText((null as any),'\n\n	',(null as any));
    this._anchor_21 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._appEl_21 = new import3.AppElement(21,19,this,this._anchor_21);
    this._TemplateRef_21_5 = new import36.TemplateRef_(this._appEl_21,viewFactory_Invite1);
    this._NgIf_21_6 = new import21.Wrapper_NgIf(this._appEl_21.vcRef,this._TemplateRef_21_5);
    this._text_22 = this.renderer.createText((null as any),'\n\n	',(null as any));
    this._el_23 = this.renderer.createElement((null as any),'ion-list',(null as any));
    this._List_23_3 = new import22.Wrapper_List(this.parentInjector.get(import26.Config),new import27.ElementRef(this._el_23),this.renderer,this.parentInjector.get(import37.GestureController));
    this._text_24 = this.renderer.createText(this._el_23,'\n		',(null as any));
    this._anchor_25 = this.renderer.createTemplateAnchor(this._el_23,(null as any));
    this._appEl_25 = new import3.AppElement(25,23,this,this._anchor_25);
    this._TemplateRef_25_5 = new import36.TemplateRef_(this._appEl_25,viewFactory_Invite2);
    this._NgFor_25_6 = new import23.Wrapper_NgFor(this._appEl_25.vcRef,this._TemplateRef_25_5,this.parentInjector.get(import38.IterableDiffers),this.ref);
    this._text_26 = this.renderer.createText(this._el_23,'\n	',(null as any));
    this._text_27 = this.renderer.createText((null as any),'\n\n	',(null as any));
    this._anchor_28 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._appEl_28 = new import3.AppElement(28,19,this,this._anchor_28);
    this._TemplateRef_28_5 = new import36.TemplateRef_(this._appEl_28,viewFactory_Invite6);
    this._NgIf_28_6 = new import21.Wrapper_NgIf(this._appEl_28.vcRef,this._TemplateRef_28_5);
    this._text_29 = this.renderer.createText((null as any),'\n\n	',(null as any));
    this._el_30 = this.renderer.createElement((null as any),'ion-infinite-scroll',(null as any));
    this._InfiniteScroll_30_3 = new import24.Wrapper_InfiniteScroll(this._Content_19_4.context,this.parentInjector.get(import34.NgZone),new import27.ElementRef(this._el_30));
    this._text_31 = this.renderer.createText(this._el_30,'\n		',(null as any));
    this._el_32 = this.renderer.createElement(this._el_30,'ion-infinite-scroll-content',(null as any));
    this._appEl_32 = new import3.AppElement(32,30,this,this._el_32);
    var compView_32:any = import25.viewFactory_InfiniteScrollContent0(this.viewUtils,this.injector(32),this._appEl_32);
    this._InfiniteScrollContent_32_4 = new import25.Wrapper_InfiniteScrollContent(this._InfiniteScroll_30_3.context,this.parentInjector.get(import26.Config));
    this._appEl_32.initComponent(this._InfiniteScrollContent_32_4.context,([] as any[]),compView_32);
    compView_32.create(this._InfiniteScrollContent_32_4.context,([] as any[]),(null as any));
    this._text_33 = this.renderer.createText(this._el_30,'\n	',(null as any));
    this._text_34 = this.renderer.createText((null as any),'\n\n',(null as any));
    compView_19.create(this._Content_19_4.context,[
      ([] as any[]),
      ([] as any[]).concat([
        this._text_20,
        this._appEl_21,
        this._text_22,
        this._el_23,
        this._text_27,
        this._appEl_28,
        this._text_29,
        this._el_30,
        this._text_34
      ]
      ),
      ([] as any[])
    ]
    ,(null as any));
    this._text_35 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_6,'click',this.eventHandler(this._handle_click_6_0.bind(this)));
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    var disposable_1:Function = this.renderer.listen(this._el_16,'ionInput',this.eventHandler(this._handle_ionInput_16_0.bind(this)));
    this._expr_8 = import7.UNINITIALIZED;
    this._expr_9 = import7.UNINITIALIZED;
    this._expr_10 = import7.UNINITIALIZED;
    this._expr_11 = import7.UNINITIALIZED;
    this._expr_12 = import7.UNINITIALIZED;
    this._expr_13 = import7.UNINITIALIZED;
    const subscription_0:any = this._Searchbar_16_4.context.ionInput.subscribe(this.eventHandler(this._handle_ionInput_16_0.bind(this)));
    this._expr_14 = import7.UNINITIALIZED;
    var disposable_2:Function = this.renderer.listen(this._el_30,'ionInfinite',this.eventHandler(this._handle_ionInfinite_30_0.bind(this)));
    const subscription_1:any = this._InfiniteScroll_30_3.context.ionInfinite.subscribe(this.eventHandler(this._handle_ionInfinite_30_0.bind(this)));
    this._expr_19 = import7.UNINITIALIZED;
    this.init(([] as any[]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._text_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._text_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._anchor_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._anchor_25,
      this._text_26,
      this._text_27,
      this._anchor_28,
      this._text_29,
      this._el_30,
      this._text_31,
      this._el_32,
      this._text_33,
      this._text_34,
      this._text_35
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2
    ]
    ,[
      subscription_0,
      subscription_1
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import39.Icon) && (8 === requestNodeIndex))) { return this._Icon_8_3.context; }
    if (((token === import40.Button) && ((6 <= requestNodeIndex) && (requestNodeIndex <= 9)))) { return this._Button_6_4.context; }
    if (((token === import41.MenuToggle) && ((6 <= requestNodeIndex) && (requestNodeIndex <= 9)))) { return this._MenuToggle_6_5.context; }
    if (((token === import42.ToolbarItem) && ((6 <= requestNodeIndex) && (requestNodeIndex <= 9)))) { return this._ToolbarItem_6_6.context; }
    if (((token === import42.ToolbarItem) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 10)))) { return this._ToolbarItem_4_3.context; }
    if (((token === import43.ToolbarTitle) && ((12 <= requestNodeIndex) && (requestNodeIndex <= 13)))) { return this._ToolbarTitle_12_4.context; }
    if (((token === import44.Navbar) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 14)))) { return this._Navbar_2_4.context; }
    if (((token === import45.Searchbar) && (16 === requestNodeIndex))) { return this._Searchbar_16_4.context; }
    if (((token === import30.Header) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 17)))) { return this._Header_0_3.context; }
    if (((token === import36.TemplateRef) && (21 === requestNodeIndex))) { return this._TemplateRef_21_5; }
    if (((token === import46.NgIf) && (21 === requestNodeIndex))) { return this._NgIf_21_6.context; }
    if (((token === import36.TemplateRef) && (25 === requestNodeIndex))) { return this._TemplateRef_25_5; }
    if (((token === import47.NgFor) && (25 === requestNodeIndex))) { return this._NgFor_25_6.context; }
    if (((token === import48.List) && ((23 <= requestNodeIndex) && (requestNodeIndex <= 26)))) { return this._List_23_3.context; }
    if (((token === import36.TemplateRef) && (28 === requestNodeIndex))) { return this._TemplateRef_28_5; }
    if (((token === import46.NgIf) && (28 === requestNodeIndex))) { return this._NgIf_28_6.context; }
    if (((token === import49.InfiniteScrollContent) && (32 === requestNodeIndex))) { return this._InfiniteScrollContent_32_4.context; }
    if (((token === import50.InfiniteScroll) && ((30 <= requestNodeIndex) && (requestNodeIndex <= 33)))) { return this._InfiniteScroll_30_3.context; }
    if (((token === import51.Content) && ((19 <= requestNodeIndex) && (requestNodeIndex <= 34)))) { return this._Content_19_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._Header_0_3.detectChangesInternal(this,this._el_0,throwOnChange);
    this._Navbar_2_4.detectChangesInternal(this,this._el_2,throwOnChange);
    this._ToolbarItem_4_3.detectChangesInternal(this,this._el_4,throwOnChange);
    if (this._Button_6_4.detectChangesInternal(this,this._el_6,throwOnChange)) { this._appEl_6.componentView.markAsCheckOnce(); }
    const currVal_3:any = '';
    this._MenuToggle_6_5.check_menuToggle(currVal_3,throwOnChange,false);
    this._MenuToggle_6_5.detectChangesInternal(this,this._el_6,throwOnChange);
    this._ToolbarItem_6_6.detectChangesInternal(this,this._el_6,throwOnChange);
    const currVal_5:any = 'menu';
    this._Icon_8_3.check_name(currVal_5,throwOnChange,false);
    this._Icon_8_3.detectChangesInternal(this,this._el_8,throwOnChange);
    if (this._ToolbarTitle_12_4.detectChangesInternal(this,this._el_12,throwOnChange)) { this._appEl_12.componentView.markAsCheckOnce(); }
    this._Searchbar_16_4.detectChangesInternal(this,this._el_16,throwOnChange);
    if (this._Content_19_4.detectChangesInternal(this,this._el_19,throwOnChange)) { this._appEl_19.componentView.markAsCheckOnce(); }
    const currVal_15:any = ((this.context.contacts.length <= 0) && !this.context.loadingContacts);
    this._NgIf_21_6.check_ngIf(currVal_15,throwOnChange,false);
    this._NgIf_21_6.detectChangesInternal(this,this._anchor_21,throwOnChange);
    this._List_23_3.detectChangesInternal(this,this._el_23,throwOnChange);
    const currVal_16:any = this.context.contacts;
    this._NgFor_25_6.check_ngForOf(currVal_16,throwOnChange,false);
    this._NgFor_25_6.detectChangesInternal(this,this._anchor_25,throwOnChange);
    const currVal_17:any = this.context.loadingContacts;
    this._NgIf_28_6.check_ngIf(currVal_17,throwOnChange,false);
    this._NgIf_28_6.detectChangesInternal(this,this._anchor_28,throwOnChange);
    this._InfiniteScroll_30_3.detectChangesInternal(this,this._el_30,throwOnChange);
    this._InfiniteScrollContent_32_4.detectChangesInternal(this,this._el_32,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_6_0.dirty) {
        this._query_Button_6_0.reset([this._Button_6_4.context]);
        this._ToolbarItem_6_6.context._buttons = this._query_Button_6_0;
        this._query_Button_6_0.notifyOnChanges();
      }
      if (this._query_Button_4_0.dirty) {
        this._query_Button_4_0.reset([this._Button_6_4.context]);
        this._ToolbarItem_4_3.context._buttons = this._query_Button_4_0;
        this._query_Button_4_0.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Button_6_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Searchbar_16_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._InfiniteScroll_30_3.context.ngAfterContentInit(); }
    }
    const currVal_0:any = this._Navbar_2_4.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_2,'hidden',currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = this._Navbar_2_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementClass(this._el_2,'statusbar-padding',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_4:any = this._MenuToggle_6_5.context.isHidden;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementProperty(this._el_6,'hidden',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_6:any = this._Icon_8_3.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementClass(this._el_8,'hide',currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_8:any = this._Searchbar_16_4.context.animated;
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementClass(this._el_16,'searchbar-animated',currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_9:any = this._Searchbar_16_4.context._value;
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setElementClass(this._el_16,'searchbar-has-value',currVal_9);
      this._expr_9 = currVal_9;
    }
    const currVal_10:any = this._Searchbar_16_4.context._isActive;
    if (import4.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this.renderer.setElementClass(this._el_16,'searchbar-active',currVal_10);
      this._expr_10 = currVal_10;
    }
    const currVal_11:any = this._Searchbar_16_4.context.showCancelButton;
    if (import4.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this.renderer.setElementClass(this._el_16,'searchbar-show-cancel',currVal_11);
      this._expr_11 = currVal_11;
    }
    const currVal_12:any = this._Searchbar_16_4.context._shouldAlignLeft;
    if (import4.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this.renderer.setElementClass(this._el_16,'searchbar-left-aligned',currVal_12);
      this._expr_12 = currVal_12;
    }
    const currVal_13:any = this._Searchbar_16_4.context._sbHasFocus;
    if (import4.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this.renderer.setElementClass(this._el_16,'searchbar-has-focus',currVal_13);
      this._expr_13 = currVal_13;
    }
    const currVal_14:any = this._Content_19_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this.renderer.setElementClass(this._el_19,'statusbar-padding',currVal_14);
      this._expr_14 = currVal_14;
    }
    const currVal_19:any = this._InfiniteScrollContent_32_4.context.inf.state;
    if (import4.checkBinding(throwOnChange,this._expr_19,currVal_19)) {
      this.renderer.setElementAttribute(this._el_32,'state',((currVal_19 == (null as any))? (null as any): currVal_19.toString()));
      this._expr_19 = currVal_19;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Navbar_2_4.context.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._Icon_8_3.context.ngOnDestroy();
    this._InfiniteScroll_30_3.context.ngOnDestroy();
    this._Content_19_4.context.ngOnDestroy();
  }
  private _handle_click_6_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._MenuToggle_6_5.context.toggle()) !== false);
    return (true && pd_0);
  }
  private _handle_ionInput_16_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.updateContactsList($event)) !== false);
    return (true && pd_0);
  }
  private _handle_ionInfinite_30_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.loadMoreContacts($event)) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_Invite0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.Invite> {
  if ((renderType_Invite === (null as any))) { (renderType_Invite = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,styles_Invite,{})); }
  return new _View_Invite0(viewUtils,parentInjector,declarationEl);
}
class _View_Invite1 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _Item_0_4:import52.Wrapper_Item;
  _ItemContent_0_5:import52.Wrapper_ItemContent;
  _query_Label_0_0:import14.QueryList<any>;
  _query_Button_0_1:import14.QueryList<any>;
  _query_Icon_0_2:import14.QueryList<any>;
  _text_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_Invite1,renderType_Invite,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','item item-block');
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import52.viewFactory_Item0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Item_0_4 = new import52.Wrapper_Item(this.parent.parentInjector.get(import53.Form),this.parent.parentInjector.get(import26.Config),new import27.ElementRef(this._el_0),this.renderer,this.parent.parentInjector.get(import54.ItemReorder,(null as any)));
    this._ItemContent_0_5 = new import52.Wrapper_ItemContent();
    this._query_Label_0_0 = new import14.QueryList<any>();
    this._query_Button_0_1 = new import14.QueryList<any>();
    this._query_Icon_0_2 = new import14.QueryList<any>();
    this._appEl_0.initComponent(this._Item_0_4.context,([] as any[]),compView_0);
    this._text_1 = this.renderer.createText((null as any),'No Contacts found',(null as any));
    this._query_Label_0_0.reset(([] as any[]));
    this._Item_0_4.context.contentLabel = this._query_Label_0_0.first;
    compView_0.create(this._Item_0_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([this._text_1]),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import55.Item) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._Item_0_4.context; }
    if (((token === import55.ItemContent) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._ItemContent_0_5.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (this._Item_0_4.detectChangesInternal(this,this._el_0,throwOnChange)) { this._appEl_0.componentView.markAsCheckOnce(); }
    this._ItemContent_0_5.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_0_1.dirty) {
        this._query_Button_0_1.reset(([] as any[]));
        this._Item_0_4.context._buttons = this._query_Button_0_1;
        this._query_Button_0_1.notifyOnChanges();
      }
      if (this._query_Icon_0_2.dirty) {
        this._query_Icon_0_2.reset(([] as any[]));
        this._Item_0_4.context._icons = this._query_Icon_0_2;
        this._query_Icon_0_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Item_0_4.context.ngAfterContentInit(); }
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_Invite1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_Invite1(viewUtils,parentInjector,declarationEl);
}
class _View_Invite2 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _Item_0_4:import52.Wrapper_Item;
  _ItemContent_0_5:import52.Wrapper_ItemContent;
  _query_Label_0_0:import14.QueryList<any>;
  _query_Button_0_1:import14.QueryList<any>;
  _query_Icon_0_2:import14.QueryList<any>;
  _text_1:any;
  _el_2:any;
  _Avatar_2_3:import56.Wrapper_Avatar;
  _text_3:any;
  _anchor_4:any;
  /*private*/ _appEl_4:import3.AppElement;
  _TemplateRef_4_5:any;
  _NgIf_4_6:import21.Wrapper_NgIf;
  _text_5:any;
  _anchor_6:any;
  /*private*/ _appEl_6:import3.AppElement;
  _TemplateRef_6_5:any;
  _NgIf_6_6:import21.Wrapper_NgIf;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  _NgClass_9_3:import57.Wrapper_NgClass;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _text_13:any;
  _text_14:any;
  _anchor_15:any;
  /*private*/ _appEl_15:import3.AppElement;
  _TemplateRef_15_5:any;
  _NgIf_15_6:import21.Wrapper_NgIf;
  _text_16:any;
  _map_0:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_Invite2,renderType_Invite,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','item item-block');
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import52.viewFactory_Item0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Item_0_4 = new import52.Wrapper_Item(this.parent.parentInjector.get(import53.Form),this.parent.parentInjector.get(import26.Config),new import27.ElementRef(this._el_0),this.renderer,this.parent.parentInjector.get(import54.ItemReorder,(null as any)));
    this._ItemContent_0_5 = new import52.Wrapper_ItemContent();
    this._query_Label_0_0 = new import14.QueryList<any>();
    this._query_Button_0_1 = new import14.QueryList<any>();
    this._query_Icon_0_2 = new import14.QueryList<any>();
    this._appEl_0.initComponent(this._Item_0_4.context,([] as any[]),compView_0);
    this._text_1 = this.renderer.createText((null as any),'\n			',(null as any));
    this._el_2 = this.renderer.createElement((null as any),'ion-avatar',(null as any));
    this.renderer.setElementAttribute(this._el_2,'item-left','');
    this._Avatar_2_3 = new import56.Wrapper_Avatar();
    this._text_3 = this.renderer.createText(this._el_2,'\n				',(null as any));
    this._anchor_4 = this.renderer.createTemplateAnchor(this._el_2,(null as any));
    this._appEl_4 = new import3.AppElement(4,2,this,this._anchor_4);
    this._TemplateRef_4_5 = new import36.TemplateRef_(this._appEl_4,viewFactory_Invite3);
    this._NgIf_4_6 = new import21.Wrapper_NgIf(this._appEl_4.vcRef,this._TemplateRef_4_5);
    this._text_5 = this.renderer.createText(this._el_2,'\n				',(null as any));
    this._anchor_6 = this.renderer.createTemplateAnchor(this._el_2,(null as any));
    this._appEl_6 = new import3.AppElement(6,2,this,this._anchor_6);
    this._TemplateRef_6_5 = new import36.TemplateRef_(this._appEl_6,viewFactory_Invite4);
    this._NgIf_6_6 = new import21.Wrapper_NgIf(this._appEl_6.vcRef,this._TemplateRef_6_5);
    this._text_7 = this.renderer.createText(this._el_2,'\n			',(null as any));
    this._text_8 = this.renderer.createText((null as any),'\n			',(null as any));
    this._el_9 = this.renderer.createElement((null as any),'h2',(null as any));
    this._NgClass_9_3 = new import57.Wrapper_NgClass(this.parent.parentInjector.get(import38.IterableDiffers),this.parent.parentInjector.get(import58.KeyValueDiffers),new import27.ElementRef(this._el_9),this.renderer);
    this._text_10 = this.renderer.createText(this._el_9,'\n				',(null as any));
    this._el_11 = this.renderer.createElement(this._el_9,'B',(null as any));
    this._text_12 = this.renderer.createText(this._el_11,'',(null as any));
    this._text_13 = this.renderer.createText(this._el_9,'',(null as any));
    this._text_14 = this.renderer.createText((null as any),'\n			',(null as any));
    this._anchor_15 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._appEl_15 = new import3.AppElement(15,0,this,this._anchor_15);
    this._TemplateRef_15_5 = new import36.TemplateRef_(this._appEl_15,viewFactory_Invite5);
    this._NgIf_15_6 = new import21.Wrapper_NgIf(this._appEl_15.vcRef,this._TemplateRef_15_5);
    this._text_16 = this.renderer.createText((null as any),'\n		',(null as any));
    this._query_Label_0_0.reset(([] as any[]));
    this._Item_0_4.context.contentLabel = this._query_Label_0_0.first;
    compView_0.create(this._Item_0_4.context,[
      ([] as any[]).concat([this._el_2]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_1,
        this._text_8,
        this._el_9,
        this._text_14,
        this._appEl_15,
        this._text_16
      ]
      ),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_0,'click',this.eventHandler(this._handle_click_0_0.bind(this)));
    this._map_0 = import4.pureProxy1((p0:any):{[key: string]:any} => {
      return {disabled: p0};
    });
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._anchor_4,
      this._text_5,
      this._anchor_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._text_13,
      this._text_14,
      this._anchor_15,
      this._text_16
    ]
    ,[disposable_0],([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import36.TemplateRef) && (4 === requestNodeIndex))) { return this._TemplateRef_4_5; }
    if (((token === import46.NgIf) && (4 === requestNodeIndex))) { return this._NgIf_4_6.context; }
    if (((token === import36.TemplateRef) && (6 === requestNodeIndex))) { return this._TemplateRef_6_5; }
    if (((token === import46.NgIf) && (6 === requestNodeIndex))) { return this._NgIf_6_6.context; }
    if (((token === import59.Avatar) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._Avatar_2_3.context; }
    if (((token === import60.NgClass) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 13)))) { return this._NgClass_9_3.context; }
    if (((token === import36.TemplateRef) && (15 === requestNodeIndex))) { return this._TemplateRef_15_5; }
    if (((token === import46.NgIf) && (15 === requestNodeIndex))) { return this._NgIf_15_6.context; }
    if (((token === import55.Item) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 16)))) { return this._Item_0_4.context; }
    if (((token === import55.ItemContent) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 16)))) { return this._ItemContent_0_5.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (this._Item_0_4.detectChangesInternal(this,this._el_0,throwOnChange)) { this._appEl_0.componentView.markAsCheckOnce(); }
    this._ItemContent_0_5.detectChangesInternal(this,this._el_0,throwOnChange);
    this._Avatar_2_3.detectChangesInternal(this,this._el_2,throwOnChange);
    const currVal_1:any = (((this.context.$implicit.photos && this.context.$implicit.photos[0]) && this.context.$implicit.photos[0].value) && (this.context.$implicit.photos[0].value !== ''));
    this._NgIf_4_6.check_ngIf(currVal_1,throwOnChange,false);
    this._NgIf_4_6.detectChangesInternal(this,this._anchor_4,throwOnChange);
    const currVal_2:boolean = (((!this.context.$implicit.photos || !this.context.$implicit.photos[0]) || !this.context.$implicit.photos[0].value) || (this.context.$implicit.photos[0].value === ''));
    this._NgIf_6_6.check_ngIf(currVal_2,throwOnChange,false);
    this._NgIf_6_6.detectChangesInternal(this,this._anchor_6,throwOnChange);
    const currVal_3:any = this._map_0((!this.context.$implicit.phoneNumbers && !this.context.$implicit.emails));
    this._NgClass_9_3.check_ngClass(currVal_3,throwOnChange,false);
    this._NgClass_9_3.detectChangesInternal(this,this._el_9,throwOnChange);
    const currVal_6:boolean = (!this.context.$implicit.phoneNumbers && !this.context.$implicit.emails);
    this._NgIf_15_6.check_ngIf(currVal_6,throwOnChange,false);
    this._NgIf_15_6.detectChangesInternal(this,this._anchor_15,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_0_1.dirty) {
        this._query_Button_0_1.reset(([] as any[]));
        this._Item_0_4.context._buttons = this._query_Button_0_1;
        this._query_Button_0_1.notifyOnChanges();
      }
      if (this._query_Icon_0_2.dirty) {
        this._query_Icon_0_2.reset(([] as any[]));
        this._Item_0_4.context._icons = this._query_Icon_0_2;
        this._query_Icon_0_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Item_0_4.context.ngAfterContentInit(); }
    }
    const currVal_4:any = import4.interpolate(1,'',this.context.$implicit.name.givenName,'');
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setText(this._text_12,currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = import4.interpolate(1,' ',this.context.$implicit.name.familyName,'\n			');
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setText(this._text_13,currVal_5);
      this._expr_5 = currVal_5;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_click_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.messageInvitee(this.context.$implicit)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_Invite2(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_Invite2(viewUtils,parentInjector,declarationEl);
}
class _View_Invite3 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_Invite3,renderType_Invite,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'img',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = this.parent.context.$implicit.photos[0].value;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_0,'src',this.viewUtils.sanitizer.sanitize(import61.SecurityContext.URL,currVal_0));
      this._expr_0 = currVal_0;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_Invite3(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_Invite3(viewUtils,parentInjector,declarationEl);
}
class _View_Invite4 extends import1.AppView<any> {
  _el_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_Invite4,renderType_Invite,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'img',(null as any));
    this.renderer.setElementAttribute(this._el_0,'src','assets/icon/Icon-NoPhoto.png');
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return (null as any);
  }
}
function viewFactory_Invite4(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_Invite4(viewUtils,parentInjector,declarationEl);
}
class _View_Invite5 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_Invite5,renderType_Invite,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'p',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'No phone or email',(null as any));
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
}
function viewFactory_Invite5(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_Invite5(viewUtils,parentInjector,declarationEl);
}
class _View_Invite6 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _Item_0_4:import52.Wrapper_Item;
  _ItemContent_0_5:import52.Wrapper_ItemContent;
  _query_Label_0_0:import14.QueryList<any>;
  _query_Button_0_1:import14.QueryList<any>;
  _query_Icon_0_2:import14.QueryList<any>;
  _text_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_Invite6,renderType_Invite,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','item item-block');
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import52.viewFactory_Item0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Item_0_4 = new import52.Wrapper_Item(this.parent.parentInjector.get(import53.Form),this.parent.parentInjector.get(import26.Config),new import27.ElementRef(this._el_0),this.renderer,this.parent.parentInjector.get(import54.ItemReorder,(null as any)));
    this._ItemContent_0_5 = new import52.Wrapper_ItemContent();
    this._query_Label_0_0 = new import14.QueryList<any>();
    this._query_Button_0_1 = new import14.QueryList<any>();
    this._query_Icon_0_2 = new import14.QueryList<any>();
    this._appEl_0.initComponent(this._Item_0_4.context,([] as any[]),compView_0);
    this._text_1 = this.renderer.createText((null as any),'Loading Contacts...',(null as any));
    this._query_Label_0_0.reset(([] as any[]));
    this._Item_0_4.context.contentLabel = this._query_Label_0_0.first;
    compView_0.create(this._Item_0_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([this._text_1]),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import55.Item) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._Item_0_4.context; }
    if (((token === import55.ItemContent) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._ItemContent_0_5.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (this._Item_0_4.detectChangesInternal(this,this._el_0,throwOnChange)) { this._appEl_0.componentView.markAsCheckOnce(); }
    this._ItemContent_0_5.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_0_1.dirty) {
        this._query_Button_0_1.reset(([] as any[]));
        this._Item_0_4.context._buttons = this._query_Button_0_1;
        this._query_Button_0_1.notifyOnChanges();
      }
      if (this._query_Icon_0_2.dirty) {
        this._query_Icon_0_2.reset(([] as any[]));
        this._Item_0_4.context._icons = this._query_Icon_0_2;
        this._query_Icon_0_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Item_0_4.context.ngAfterContentInit(); }
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_Invite6(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_Invite6(viewUtils,parentInjector,declarationEl);
}