/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from './invite-details';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from 'ionic-angular/navigation/nav-controller';
import * as import9 from 'ionic-angular/navigation/nav-params';
import * as import10 from 'ionic-angular/platform/platform';
import * as import11 from '@angular/platform-browser/src/security/dom_sanitization_service';
import * as import12 from '@angular/core/src/metadata/view';
import * as import13 from '@angular/core/src/linker/component_factory';
import * as import14 from '@angular/core/src/linker/query_list';
import * as import15 from '../../node_modules/ionic-angular/components/toolbar/toolbar.ngfactory';
import * as import16 from '../../node_modules/ionic-angular/components/navbar/navbar.ngfactory';
import * as import17 from '../../node_modules/ionic-angular/components/toolbar/toolbar-item.ngfactory';
import * as import18 from '../../node_modules/ionic-angular/components/button/button.ngfactory';
import * as import19 from '../../node_modules/ionic-angular/components/menu/menu-toggle.ngfactory';
import * as import20 from '../../node_modules/ionic-angular/components/icon/icon.ngfactory';
import * as import21 from '../../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import22 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import23 from '../../node_modules/ionic-angular/components/card/card.ngfactory';
import * as import24 from '../../node_modules/ionic-angular/components/item/item.ngfactory';
import * as import25 from '../../node_modules/ionic-angular/components/avatar/avatar.ngfactory';
import * as import26 from '../../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import27 from '../../node_modules/@angular/common/src/directives/ng_for.ngfactory';
import * as import28 from 'ionic-angular/config/config';
import * as import29 from '@angular/core/src/linker/element_ref';
import * as import30 from 'ionic-angular/navigation/view-controller';
import * as import31 from 'ionic-angular/components/app/app';
import * as import32 from 'ionic-angular/components/toolbar/toolbar';
import * as import33 from 'ionic-angular/components/menu/menu-controller';
import * as import34 from 'ionic-angular/util/keyboard';
import * as import35 from '@angular/core/src/zone/ng_zone';
import * as import36 from 'ionic-angular/components/tabs/tabs';
import * as import37 from 'ionic-angular/util/form';
import * as import38 from 'ionic-angular/components/item/item-reorder';
import * as import39 from '@angular/core/src/linker/template_ref';
import * as import40 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import41 from 'ionic-angular/components/icon/icon';
import * as import42 from 'ionic-angular/components/button/button';
import * as import43 from 'ionic-angular/components/menu/menu-toggle';
import * as import44 from 'ionic-angular/components/toolbar/toolbar-item';
import * as import45 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import46 from 'ionic-angular/components/navbar/navbar';
import * as import47 from '@angular/common/src/directives/ng_if';
import * as import48 from 'ionic-angular/components/avatar/avatar';
import * as import49 from 'ionic-angular/components/item/item';
import * as import50 from 'ionic-angular/components/card/card';
import * as import51 from '@angular/common/src/directives/ng_for';
import * as import52 from 'ionic-angular/components/content/content';
import * as import53 from '@angular/core/src/security';
export class Wrapper_InviteDetails {
  context:import0.InviteDetails;
  changed:boolean;
  constructor(p0:any,p1:any,p2:any,p3:any) {
    this.changed = false;
    this.context = new import0.InviteDetails(p0,p1,p2,p3);
  }
  detectChangesInternal(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
}
var renderType_InviteDetails_Host:import2.RenderComponentType = (null as any);
class _View_InviteDetails_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _InviteDetails_0_4:Wrapper_InviteDetails;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_InviteDetails_Host0,renderType_InviteDetails_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.selectOrCreateHostElement('page-invite-details',rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_InviteDetails0(this.viewUtils,this.injector(0),this._appEl_0);
    this._InviteDetails_0_4 = new Wrapper_InviteDetails(this.parentInjector.get(import8.NavController),this.parentInjector.get(import9.NavParams),this.parentInjector.get(import10.Platform),this.parentInjector.get(import11.DomSanitizer));
    this._appEl_0.initComponent(this._InviteDetails_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._InviteDetails_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.InviteDetails) && (0 === requestNodeIndex))) { return this._InviteDetails_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._InviteDetails_0_4.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_InviteDetails_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_InviteDetails_Host === (null as any))) { (renderType_InviteDetails_Host = viewUtils.createRenderComponentType('',0,import12.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_InviteDetails_Host0(viewUtils,parentInjector,declarationEl);
}
export const InviteDetailsNgFactory:import13.ComponentFactory<import0.InviteDetails> = new import13.ComponentFactory<import0.InviteDetails>('page-invite-details',viewFactory_InviteDetails_Host0,import0.InviteDetails);
const styles_InviteDetails:any[] = ([] as any[]);
var renderType_InviteDetails:import2.RenderComponentType = (null as any);
class _View_InviteDetails0 extends import1.AppView<import0.InviteDetails> {
  _viewQuery_Content_0:import14.QueryList<any>;
  _el_0:any;
  _Header_0_3:import15.Wrapper_Header;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import3.AppElement;
  _Navbar_2_4:import16.Wrapper_Navbar;
  _text_3:any;
  _el_4:any;
  _ToolbarItem_4_3:import17.Wrapper_ToolbarItem;
  _query_Button_4_0:import14.QueryList<any>;
  _text_5:any;
  _el_6:any;
  /*private*/ _appEl_6:import3.AppElement;
  _Button_6_4:import18.Wrapper_Button;
  _MenuToggle_6_5:import19.Wrapper_MenuToggle;
  _ToolbarItem_6_6:import17.Wrapper_ToolbarItem;
  _query_Button_6_0:import14.QueryList<any>;
  _text_7:any;
  _el_8:any;
  _Icon_8_3:import20.Wrapper_Icon;
  _text_9:any;
  _text_10:any;
  _text_11:any;
  _el_12:any;
  /*private*/ _appEl_12:import3.AppElement;
  _ToolbarTitle_12_4:import21.Wrapper_ToolbarTitle;
  _text_13:any;
  _text_14:any;
  _text_15:any;
  _text_16:any;
  _el_17:any;
  /*private*/ _appEl_17:import3.AppElement;
  _Content_17_4:import22.Wrapper_Content;
  _text_18:any;
  _el_19:any;
  _Card_19_3:import23.Wrapper_Card;
  _text_20:any;
  _el_21:any;
  _CardHeader_21_3:import23.Wrapper_CardHeader;
  _text_22:any;
  _el_23:any;
  /*private*/ _appEl_23:import3.AppElement;
  _Item_23_4:import24.Wrapper_Item;
  _ItemContent_23_5:import24.Wrapper_ItemContent;
  _query_Label_23_0:import14.QueryList<any>;
  _query_Button_23_1:import14.QueryList<any>;
  _query_Icon_23_2:import14.QueryList<any>;
  _text_24:any;
  _el_25:any;
  _Avatar_25_3:import25.Wrapper_Avatar;
  _text_26:any;
  _anchor_27:any;
  /*private*/ _appEl_27:import3.AppElement;
  _TemplateRef_27_5:any;
  _NgIf_27_6:import26.Wrapper_NgIf;
  _text_28:any;
  _anchor_29:any;
  /*private*/ _appEl_29:import3.AppElement;
  _TemplateRef_29_5:any;
  _NgIf_29_6:import26.Wrapper_NgIf;
  _text_30:any;
  _text_31:any;
  _el_32:any;
  _text_33:any;
  _text_34:any;
  _text_35:any;
  _text_36:any;
  _el_37:any;
  /*private*/ _appEl_37:import3.AppElement;
  _Item_37_4:import24.Wrapper_Item;
  _ItemContent_37_5:import24.Wrapper_ItemContent;
  _query_Label_37_0:import14.QueryList<any>;
  _query_Button_37_1:import14.QueryList<any>;
  _query_Icon_37_2:import14.QueryList<any>;
  _text_38:any;
  _anchor_39:any;
  /*private*/ _appEl_39:import3.AppElement;
  _TemplateRef_39_5:any;
  _NgIf_39_6:import26.Wrapper_NgIf;
  _text_40:any;
  _anchor_41:any;
  /*private*/ _appEl_41:import3.AppElement;
  _TemplateRef_41_5:any;
  _NgFor_41_6:import27.Wrapper_NgFor;
  _text_42:any;
  _anchor_43:any;
  /*private*/ _appEl_43:import3.AppElement;
  _TemplateRef_43_5:any;
  _NgIf_43_6:import26.Wrapper_NgIf;
  _text_44:any;
  _anchor_45:any;
  /*private*/ _appEl_45:import3.AppElement;
  _TemplateRef_45_5:any;
  _NgFor_45_6:import27.Wrapper_NgFor;
  _text_46:any;
  _text_47:any;
  _text_48:any;
  _text_49:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_11:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_InviteDetails0,renderType_InviteDetails,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._viewQuery_Content_0 = new import14.QueryList<any>();
    this._el_0 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this._Header_0_3 = new import15.Wrapper_Header(this.parentInjector.get(import28.Config),new import29.ElementRef(this._el_0),this.renderer,this.parentInjector.get(import30.ViewController,(null as any)));
    this._text_1 = this.renderer.createText(this._el_0,'\n	',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-navbar',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','toolbar');
    this._appEl_2 = new import3.AppElement(2,0,this,this._el_2);
    var compView_2:any = import16.viewFactory_Navbar0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Navbar_2_4 = new import16.Wrapper_Navbar(this.parentInjector.get(import31.App),this.parentInjector.get(import30.ViewController,(null as any)),this.parentInjector.get(import8.NavController,(null as any)),this.parentInjector.get(import28.Config),new import29.ElementRef(this._el_2),this.renderer);
    this._appEl_2.initComponent(this._Navbar_2_4.context,([] as any[]),compView_2);
    this._text_3 = this.renderer.createText((null as any),'\n		',(null as any));
    this._el_4 = this.renderer.createElement((null as any),'ion-buttons',(null as any));
    this.renderer.setElementAttribute(this._el_4,'start','');
    this._ToolbarItem_4_3 = new import17.Wrapper_ToolbarItem(this.parentInjector.get(import28.Config),new import29.ElementRef(this._el_4),this.renderer,this.parentInjector.get(import32.Toolbar,(null as any)),this._Navbar_2_4.context);
    this._query_Button_4_0 = new import14.QueryList<any>();
    this._text_5 = this.renderer.createText(this._el_4,'\n			',(null as any));
    this._el_6 = this.renderer.createElement(this._el_4,'button',(null as any));
    this.renderer.setElementAttribute(this._el_6,'ion-button','');
    this.renderer.setElementAttribute(this._el_6,'menuToggle','');
    this._appEl_6 = new import3.AppElement(6,4,this,this._el_6);
    var compView_6:any = import18.viewFactory_Button0(this.viewUtils,this.injector(6),this._appEl_6);
    this._Button_6_4 = new import18.Wrapper_Button('','',this.parentInjector.get(import28.Config),new import29.ElementRef(this._el_6),this.renderer);
    this._MenuToggle_6_5 = new import19.Wrapper_MenuToggle(this.parentInjector.get(import33.MenuController),new import29.ElementRef(this._el_6),this.parentInjector.get(import30.ViewController,(null as any)),this._Navbar_2_4.context);
    this._ToolbarItem_6_6 = new import17.Wrapper_ToolbarItem(this.parentInjector.get(import28.Config),new import29.ElementRef(this._el_6),this.renderer,this.parentInjector.get(import32.Toolbar,(null as any)),this._Navbar_2_4.context);
    this._query_Button_6_0 = new import14.QueryList<any>();
    this._appEl_6.initComponent(this._Button_6_4.context,([] as any[]),compView_6);
    this._text_7 = this.renderer.createText((null as any),'\n				',(null as any));
    this._el_8 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_8,'name','menu');
    this.renderer.setElementAttribute(this._el_8,'role','img');
    this._Icon_8_3 = new import20.Wrapper_Icon(this.parentInjector.get(import28.Config),new import29.ElementRef(this._el_8),this.renderer);
    this._text_9 = this.renderer.createText((null as any),'\n			',(null as any));
      compView_6.create(this._Button_6_4.context,[([] as any[]).concat([
        this._text_7,
        this._el_8,
        this._text_9
      ]
    )],(null as any));
    this._text_10 = this.renderer.createText(this._el_4,'\n		',(null as any));
    this._text_11 = this.renderer.createText((null as any),'\n		',(null as any));
    this._el_12 = this.renderer.createElement((null as any),'ion-title',(null as any));
    this._appEl_12 = new import3.AppElement(12,2,this,this._el_12);
    var compView_12:any = import21.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(12),this._appEl_12);
    this._ToolbarTitle_12_4 = new import21.Wrapper_ToolbarTitle(this.parentInjector.get(import28.Config),new import29.ElementRef(this._el_12),this.renderer,this.parentInjector.get(import32.Toolbar,(null as any)),this._Navbar_2_4.context);
    this._appEl_12.initComponent(this._ToolbarTitle_12_4.context,([] as any[]),compView_12);
    this._text_13 = this.renderer.createText((null as any),'',(null as any));
    compView_12.create(this._ToolbarTitle_12_4.context,[([] as any[]).concat([this._text_13])],(null as any));
    this._text_14 = this.renderer.createText((null as any),'\n	',(null as any));
    compView_2.create(this._Navbar_2_4.context,[
      ([] as any[]),
      ([] as any[]).concat([this._el_4]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_3,
        this._text_11,
        this._el_12,
        this._text_14
      ]
      )
    ]
    ,(null as any));
    this._text_15 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_16 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_17 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this._appEl_17 = new import3.AppElement(17,(null as any),this,this._el_17);
    var compView_17:any = import22.viewFactory_Content0(this.viewUtils,this.injector(17),this._appEl_17);
    this._Content_17_4 = new import22.Wrapper_Content(this.parentInjector.get(import28.Config),new import29.ElementRef(this._el_17),this.renderer,this.parentInjector.get(import31.App),this.parentInjector.get(import34.Keyboard),this.parentInjector.get(import35.NgZone),this.parentInjector.get(import30.ViewController,(null as any)),this.parentInjector.get(import36.Tabs,(null as any)));
    this._appEl_17.initComponent(this._Content_17_4.context,([] as any[]),compView_17);
    this._text_18 = this.renderer.createText((null as any),'\n	',(null as any));
    this._el_19 = this.renderer.createElement((null as any),'ion-card',(null as any));
    this._Card_19_3 = new import23.Wrapper_Card(this.parentInjector.get(import28.Config),new import29.ElementRef(this._el_19),this.renderer);
    this._text_20 = this.renderer.createText(this._el_19,'\n		',(null as any));
    this._el_21 = this.renderer.createElement(this._el_19,'ion-card-header',(null as any));
    this._CardHeader_21_3 = new import23.Wrapper_CardHeader(this.parentInjector.get(import28.Config),new import29.ElementRef(this._el_21),this.renderer);
    this._text_22 = this.renderer.createText(this._el_21,'\n			',(null as any));
    this._el_23 = this.renderer.createElement(this._el_21,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_23,'class','item item-block');
    this._appEl_23 = new import3.AppElement(23,21,this,this._el_23);
    var compView_23:any = import24.viewFactory_Item0(this.viewUtils,this.injector(23),this._appEl_23);
    this._Item_23_4 = new import24.Wrapper_Item(this.parentInjector.get(import37.Form),this.parentInjector.get(import28.Config),new import29.ElementRef(this._el_23),this.renderer,this.parentInjector.get(import38.ItemReorder,(null as any)));
    this._ItemContent_23_5 = new import24.Wrapper_ItemContent();
    this._query_Label_23_0 = new import14.QueryList<any>();
    this._query_Button_23_1 = new import14.QueryList<any>();
    this._query_Icon_23_2 = new import14.QueryList<any>();
    this._appEl_23.initComponent(this._Item_23_4.context,([] as any[]),compView_23);
    this._text_24 = this.renderer.createText((null as any),'\n				',(null as any));
    this._el_25 = this.renderer.createElement((null as any),'ion-avatar',(null as any));
    this.renderer.setElementAttribute(this._el_25,'item-left','');
    this._Avatar_25_3 = new import25.Wrapper_Avatar();
    this._text_26 = this.renderer.createText(this._el_25,'\n					',(null as any));
    this._anchor_27 = this.renderer.createTemplateAnchor(this._el_25,(null as any));
    this._appEl_27 = new import3.AppElement(27,25,this,this._anchor_27);
    this._TemplateRef_27_5 = new import39.TemplateRef_(this._appEl_27,viewFactory_InviteDetails1);
    this._NgIf_27_6 = new import26.Wrapper_NgIf(this._appEl_27.vcRef,this._TemplateRef_27_5);
    this._text_28 = this.renderer.createText(this._el_25,'\n\n				',(null as any));
    this._anchor_29 = this.renderer.createTemplateAnchor(this._el_25,(null as any));
    this._appEl_29 = new import3.AppElement(29,25,this,this._anchor_29);
    this._TemplateRef_29_5 = new import39.TemplateRef_(this._appEl_29,viewFactory_InviteDetails2);
    this._NgIf_29_6 = new import26.Wrapper_NgIf(this._appEl_29.vcRef,this._TemplateRef_29_5);
    this._text_30 = this.renderer.createText(this._el_25,'\n				',(null as any));
    this._text_31 = this.renderer.createText((null as any),'\n				',(null as any));
    this._el_32 = this.renderer.createElement((null as any),'h2',(null as any));
    this._text_33 = this.renderer.createText(this._el_32,'',(null as any));
    this._text_34 = this.renderer.createText((null as any),'\n			',(null as any));
    this._query_Label_23_0.reset(([] as any[]));
    this._Item_23_4.context.contentLabel = this._query_Label_23_0.first;
    compView_23.create(this._Item_23_4.context,[
      ([] as any[]).concat([this._el_25]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_24,
        this._text_31,
        this._el_32,
        this._text_34
      ]
      ),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_35 = this.renderer.createText(this._el_21,'\n		',(null as any));
    this._text_36 = this.renderer.createText(this._el_19,'\n\n		',(null as any));
    this._el_37 = this.renderer.createElement(this._el_19,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_37,'class','item item-block');
    this._appEl_37 = new import3.AppElement(37,19,this,this._el_37);
    var compView_37:any = import24.viewFactory_Item0(this.viewUtils,this.injector(37),this._appEl_37);
    this._Item_37_4 = new import24.Wrapper_Item(this.parentInjector.get(import37.Form),this.parentInjector.get(import28.Config),new import29.ElementRef(this._el_37),this.renderer,this.parentInjector.get(import38.ItemReorder,(null as any)));
    this._ItemContent_37_5 = new import24.Wrapper_ItemContent();
    this._query_Label_37_0 = new import14.QueryList<any>();
    this._query_Button_37_1 = new import14.QueryList<any>();
    this._query_Icon_37_2 = new import14.QueryList<any>();
    this._appEl_37.initComponent(this._Item_37_4.context,([] as any[]),compView_37);
    this._text_38 = this.renderer.createText((null as any),'\n			',(null as any));
    this._anchor_39 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._appEl_39 = new import3.AppElement(39,37,this,this._anchor_39);
    this._TemplateRef_39_5 = new import39.TemplateRef_(this._appEl_39,viewFactory_InviteDetails3);
    this._NgIf_39_6 = new import26.Wrapper_NgIf(this._appEl_39.vcRef,this._TemplateRef_39_5);
    this._text_40 = this.renderer.createText((null as any),'\n			',(null as any));
    this._anchor_41 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._appEl_41 = new import3.AppElement(41,37,this,this._anchor_41);
    this._TemplateRef_41_5 = new import39.TemplateRef_(this._appEl_41,viewFactory_InviteDetails4);
    this._NgFor_41_6 = new import27.Wrapper_NgFor(this._appEl_41.vcRef,this._TemplateRef_41_5,this.parentInjector.get(import40.IterableDiffers),this.ref);
    this._text_42 = this.renderer.createText((null as any),'\n\n			',(null as any));
    this._anchor_43 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._appEl_43 = new import3.AppElement(43,37,this,this._anchor_43);
    this._TemplateRef_43_5 = new import39.TemplateRef_(this._appEl_43,viewFactory_InviteDetails5);
    this._NgIf_43_6 = new import26.Wrapper_NgIf(this._appEl_43.vcRef,this._TemplateRef_43_5);
    this._text_44 = this.renderer.createText((null as any),'\n			',(null as any));
    this._anchor_45 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._appEl_45 = new import3.AppElement(45,37,this,this._anchor_45);
    this._TemplateRef_45_5 = new import39.TemplateRef_(this._appEl_45,viewFactory_InviteDetails6);
    this._NgFor_45_6 = new import27.Wrapper_NgFor(this._appEl_45.vcRef,this._TemplateRef_45_5,this.parentInjector.get(import40.IterableDiffers),this.ref);
    this._text_46 = this.renderer.createText((null as any),'\n		',(null as any));
    this._query_Label_37_0.reset(([] as any[]));
    this._Item_37_4.context.contentLabel = this._query_Label_37_0.first;
    compView_37.create(this._Item_37_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_38,
        this._appEl_39,
        this._text_40,
        this._appEl_41,
        this._text_42,
        this._appEl_43,
        this._text_44,
        this._appEl_45,
        this._text_46
      ]
      ),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_47 = this.renderer.createText(this._el_19,'\n\n	',(null as any));
    this._text_48 = this.renderer.createText((null as any),'\n\n',(null as any));
    compView_17.create(this._Content_17_4.context,[
      ([] as any[]),
      ([] as any[]).concat([
        this._text_18,
        this._el_19,
        this._text_48
      ]
      ),
      ([] as any[])
    ]
    ,(null as any));
    this._text_49 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_6,'click',this.eventHandler(this._handle_click_6_0.bind(this)));
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    this._expr_11 = import7.UNINITIALIZED;
    this._viewQuery_Content_0.reset([this._Content_17_4.context]);
    this.context.content = this._viewQuery_Content_0.first;
    this.init(([] as any[]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._text_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._text_14,
      this._text_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._anchor_27,
      this._text_28,
      this._anchor_29,
      this._text_30,
      this._text_31,
      this._el_32,
      this._text_33,
      this._text_34,
      this._text_35,
      this._text_36,
      this._el_37,
      this._text_38,
      this._anchor_39,
      this._text_40,
      this._anchor_41,
      this._text_42,
      this._anchor_43,
      this._text_44,
      this._anchor_45,
      this._text_46,
      this._text_47,
      this._text_48,
      this._text_49
    ]
    ,[disposable_0],([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import41.Icon) && (8 === requestNodeIndex))) { return this._Icon_8_3.context; }
    if (((token === import42.Button) && ((6 <= requestNodeIndex) && (requestNodeIndex <= 9)))) { return this._Button_6_4.context; }
    if (((token === import43.MenuToggle) && ((6 <= requestNodeIndex) && (requestNodeIndex <= 9)))) { return this._MenuToggle_6_5.context; }
    if (((token === import44.ToolbarItem) && ((6 <= requestNodeIndex) && (requestNodeIndex <= 9)))) { return this._ToolbarItem_6_6.context; }
    if (((token === import44.ToolbarItem) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 10)))) { return this._ToolbarItem_4_3.context; }
    if (((token === import45.ToolbarTitle) && ((12 <= requestNodeIndex) && (requestNodeIndex <= 13)))) { return this._ToolbarTitle_12_4.context; }
    if (((token === import46.Navbar) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 14)))) { return this._Navbar_2_4.context; }
    if (((token === import32.Header) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 15)))) { return this._Header_0_3.context; }
    if (((token === import39.TemplateRef) && (27 === requestNodeIndex))) { return this._TemplateRef_27_5; }
    if (((token === import47.NgIf) && (27 === requestNodeIndex))) { return this._NgIf_27_6.context; }
    if (((token === import39.TemplateRef) && (29 === requestNodeIndex))) { return this._TemplateRef_29_5; }
    if (((token === import47.NgIf) && (29 === requestNodeIndex))) { return this._NgIf_29_6.context; }
    if (((token === import48.Avatar) && ((25 <= requestNodeIndex) && (requestNodeIndex <= 30)))) { return this._Avatar_25_3.context; }
    if (((token === import49.Item) && ((23 <= requestNodeIndex) && (requestNodeIndex <= 34)))) { return this._Item_23_4.context; }
    if (((token === import49.ItemContent) && ((23 <= requestNodeIndex) && (requestNodeIndex <= 34)))) { return this._ItemContent_23_5.context; }
    if (((token === import50.CardHeader) && ((21 <= requestNodeIndex) && (requestNodeIndex <= 35)))) { return this._CardHeader_21_3.context; }
    if (((token === import39.TemplateRef) && (39 === requestNodeIndex))) { return this._TemplateRef_39_5; }
    if (((token === import47.NgIf) && (39 === requestNodeIndex))) { return this._NgIf_39_6.context; }
    if (((token === import39.TemplateRef) && (41 === requestNodeIndex))) { return this._TemplateRef_41_5; }
    if (((token === import51.NgFor) && (41 === requestNodeIndex))) { return this._NgFor_41_6.context; }
    if (((token === import39.TemplateRef) && (43 === requestNodeIndex))) { return this._TemplateRef_43_5; }
    if (((token === import47.NgIf) && (43 === requestNodeIndex))) { return this._NgIf_43_6.context; }
    if (((token === import39.TemplateRef) && (45 === requestNodeIndex))) { return this._TemplateRef_45_5; }
    if (((token === import51.NgFor) && (45 === requestNodeIndex))) { return this._NgFor_45_6.context; }
    if (((token === import49.Item) && ((37 <= requestNodeIndex) && (requestNodeIndex <= 46)))) { return this._Item_37_4.context; }
    if (((token === import49.ItemContent) && ((37 <= requestNodeIndex) && (requestNodeIndex <= 46)))) { return this._ItemContent_37_5.context; }
    if (((token === import50.Card) && ((19 <= requestNodeIndex) && (requestNodeIndex <= 47)))) { return this._Card_19_3.context; }
    if (((token === import52.Content) && ((17 <= requestNodeIndex) && (requestNodeIndex <= 48)))) { return this._Content_17_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._Header_0_3.detectChangesInternal(this,this._el_0,throwOnChange);
    this._Navbar_2_4.detectChangesInternal(this,this._el_2,throwOnChange);
    this._ToolbarItem_4_3.detectChangesInternal(this,this._el_4,throwOnChange);
    if (this._Button_6_4.detectChangesInternal(this,this._el_6,throwOnChange)) { this._appEl_6.componentView.markAsCheckOnce(); }
    const currVal_3:any = '';
    this._MenuToggle_6_5.check_menuToggle(currVal_3,throwOnChange,false);
    this._MenuToggle_6_5.detectChangesInternal(this,this._el_6,throwOnChange);
    this._ToolbarItem_6_6.detectChangesInternal(this,this._el_6,throwOnChange);
    const currVal_5:any = 'menu';
    this._Icon_8_3.check_name(currVal_5,throwOnChange,false);
    this._Icon_8_3.detectChangesInternal(this,this._el_8,throwOnChange);
    if (this._ToolbarTitle_12_4.detectChangesInternal(this,this._el_12,throwOnChange)) { this._appEl_12.componentView.markAsCheckOnce(); }
    if (this._Content_17_4.detectChangesInternal(this,this._el_17,throwOnChange)) { this._appEl_17.componentView.markAsCheckOnce(); }
    this._Card_19_3.detectChangesInternal(this,this._el_19,throwOnChange);
    this._CardHeader_21_3.detectChangesInternal(this,this._el_21,throwOnChange);
    if (this._Item_23_4.detectChangesInternal(this,this._el_23,throwOnChange)) { this._appEl_23.componentView.markAsCheckOnce(); }
    this._ItemContent_23_5.detectChangesInternal(this,this._el_23,throwOnChange);
    this._Avatar_25_3.detectChangesInternal(this,this._el_25,throwOnChange);
    const currVal_9:any = (((this.context.invitee.photos && this.context.invitee.photos[0]) && this.context.invitee.photos[0].value) && (this.context.invitee.photos[0].value !== ''));
    this._NgIf_27_6.check_ngIf(currVal_9,throwOnChange,false);
    this._NgIf_27_6.detectChangesInternal(this,this._anchor_27,throwOnChange);
    const currVal_10:boolean = (((!this.context.invitee.photos || !this.context.invitee.photos[0]) || !this.context.invitee.photos[0].value) || (this.context.invitee.photos[0].value === ''));
    this._NgIf_29_6.check_ngIf(currVal_10,throwOnChange,false);
    this._NgIf_29_6.detectChangesInternal(this,this._anchor_29,throwOnChange);
    if (this._Item_37_4.detectChangesInternal(this,this._el_37,throwOnChange)) { this._appEl_37.componentView.markAsCheckOnce(); }
    this._ItemContent_37_5.detectChangesInternal(this,this._el_37,throwOnChange);
    const currVal_12:any = this.context.invitee.phoneNumbers;
    this._NgIf_39_6.check_ngIf(currVal_12,throwOnChange,false);
    this._NgIf_39_6.detectChangesInternal(this,this._anchor_39,throwOnChange);
    const currVal_13:any = this.context.invitee.phoneNumbers;
    this._NgFor_41_6.check_ngForOf(currVal_13,throwOnChange,false);
    this._NgFor_41_6.detectChangesInternal(this,this._anchor_41,throwOnChange);
    const currVal_14:any = this.context.invitee.emails;
    this._NgIf_43_6.check_ngIf(currVal_14,throwOnChange,false);
    this._NgIf_43_6.detectChangesInternal(this,this._anchor_43,throwOnChange);
    const currVal_15:any = this.context.invitee.emails;
    this._NgFor_45_6.check_ngForOf(currVal_15,throwOnChange,false);
    this._NgFor_45_6.detectChangesInternal(this,this._anchor_45,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_6_0.dirty) {
        this._query_Button_6_0.reset([this._Button_6_4.context]);
        this._ToolbarItem_6_6.context._buttons = this._query_Button_6_0;
        this._query_Button_6_0.notifyOnChanges();
      }
      if (this._query_Button_4_0.dirty) {
        this._query_Button_4_0.reset([this._Button_6_4.context]);
        this._ToolbarItem_4_3.context._buttons = this._query_Button_4_0;
        this._query_Button_4_0.notifyOnChanges();
      }
      if (this._query_Button_23_1.dirty) {
        this._query_Button_23_1.reset(([] as any[]));
        this._Item_23_4.context._buttons = this._query_Button_23_1;
        this._query_Button_23_1.notifyOnChanges();
      }
      if (this._query_Icon_23_2.dirty) {
        this._query_Icon_23_2.reset(([] as any[]));
        this._Item_23_4.context._icons = this._query_Icon_23_2;
        this._query_Icon_23_2.notifyOnChanges();
      }
      if (this._query_Button_37_1.dirty) {
        this._query_Button_37_1.reset(([] as any[]));
        this._Item_37_4.context._buttons = this._query_Button_37_1;
        this._query_Button_37_1.notifyOnChanges();
      }
      if (this._query_Icon_37_2.dirty) {
        this._query_Icon_37_2.reset(([] as any[]));
        this._Item_37_4.context._icons = this._query_Icon_37_2;
        this._query_Icon_37_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Button_6_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_23_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_37_4.context.ngAfterContentInit(); }
    }
    const currVal_0:any = this._Navbar_2_4.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_2,'hidden',currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = this._Navbar_2_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementClass(this._el_2,'statusbar-padding',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_4:any = this._MenuToggle_6_5.context.isHidden;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementProperty(this._el_6,'hidden',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_6:any = this._Icon_8_3.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementClass(this._el_8,'hide',currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = import4.interpolate(1,'Invite ',this.context.invitee.name.givenName,'');
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setText(this._text_13,currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = this._Content_17_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementClass(this._el_17,'statusbar-padding',currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_11:any = import4.interpolate(1,'',this.context.invitee.name.givenName,'');
    if (import4.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this.renderer.setText(this._text_33,currVal_11);
      this._expr_11 = currVal_11;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Navbar_2_4.context.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._Icon_8_3.context.ngOnDestroy();
    this._Content_17_4.context.ngOnDestroy();
  }
  private _handle_click_6_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._MenuToggle_6_5.context.toggle()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_InviteDetails0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.InviteDetails> {
  if ((renderType_InviteDetails === (null as any))) { (renderType_InviteDetails = viewUtils.createRenderComponentType('',0,import12.ViewEncapsulation.None,styles_InviteDetails,{})); }
  return new _View_InviteDetails0(viewUtils,parentInjector,declarationEl);
}
class _View_InviteDetails1 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_InviteDetails1,renderType_InviteDetails,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'img',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = this.parent.context.invitee.photos[0].value;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_0,'src',this.viewUtils.sanitizer.sanitize(import53.SecurityContext.URL,currVal_0));
      this._expr_0 = currVal_0;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_InviteDetails1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_InviteDetails1(viewUtils,parentInjector,declarationEl);
}
class _View_InviteDetails2 extends import1.AppView<any> {
  _el_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_InviteDetails2,renderType_InviteDetails,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'img',(null as any));
    this.renderer.setElementAttribute(this._el_0,'src','assets/icon/Icon-NoPhoto.png');
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return (null as any);
  }
}
function viewFactory_InviteDetails2(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_InviteDetails2(viewUtils,parentInjector,declarationEl);
}
class _View_InviteDetails3 extends import1.AppView<any> {
  _el_0:any;
  _CardTitle_0_3:import23.Wrapper_CardTitle;
  _text_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_InviteDetails3,renderType_InviteDetails,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ion-card-title',(null as any));
    this._CardTitle_0_3 = new import23.Wrapper_CardTitle(this.parent.parentInjector.get(import28.Config),new import29.ElementRef(this._el_0),this.renderer);
    this._text_1 = this.renderer.createText(this._el_0,'\n				Invite by SMS:\n			',(null as any));
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import50.CardTitle) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._CardTitle_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._CardTitle_0_3.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_InviteDetails3(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_InviteDetails3(viewUtils,parentInjector,declarationEl);
}
class _View_InviteDetails4 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_InviteDetails4,renderType_InviteDetails,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'p',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n				',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'a',(null as any));
    this.renderer.setElementAttribute(this._el_2,'style','text-decoration: none;');
    this._text_3 = this.renderer.createText(this._el_2,'',(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n			',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = this.parent.context.getSMSHrefForPhoneNumber(this.context.$implicit.value);
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_2,'href',this.viewUtils.sanitizer.sanitize(import53.SecurityContext.URL,currVal_0));
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = import4.interpolate(1,'\n					',this.context.$implicit.value,'\n				');
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setText(this._text_3,currVal_1);
      this._expr_1 = currVal_1;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_InviteDetails4(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_InviteDetails4(viewUtils,parentInjector,declarationEl);
}
class _View_InviteDetails5 extends import1.AppView<any> {
  _el_0:any;
  _CardTitle_0_3:import23.Wrapper_CardTitle;
  _text_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_InviteDetails5,renderType_InviteDetails,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ion-card-title',(null as any));
    this._CardTitle_0_3 = new import23.Wrapper_CardTitle(this.parent.parentInjector.get(import28.Config),new import29.ElementRef(this._el_0),this.renderer);
    this._text_1 = this.renderer.createText(this._el_0,'\n				Invite by Email:\n			',(null as any));
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import50.CardTitle) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._CardTitle_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._CardTitle_0_3.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_InviteDetails5(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_InviteDetails5(viewUtils,parentInjector,declarationEl);
}
class _View_InviteDetails6 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_InviteDetails6,renderType_InviteDetails,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'p',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n				',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'a',(null as any));
    this.renderer.setElementAttribute(this._el_2,'style','text-decoration: none;');
    this._text_3 = this.renderer.createText(this._el_2,'',(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n			',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = this.parent.context.getEmailHrefForEmail(this.context.$implicit.value);
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_2,'href',this.viewUtils.sanitizer.sanitize(import53.SecurityContext.URL,currVal_0));
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = import4.interpolate(1,'\n					',this.context.$implicit.value,'\n				');
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setText(this._text_3,currVal_1);
      this._expr_1 = currVal_1;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_InviteDetails6(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_InviteDetails6(viewUtils,parentInjector,declarationEl);
}