/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from './account';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '../../services/onymos-services';
import * as import5 from '@angular/core/src/linker/view_utils';
import * as import6 from '@angular/core/src/di/injector';
import * as import7 from '@angular/core/src/linker/view_type';
import * as import8 from '@angular/core/src/change_detection/change_detection';
import * as import9 from 'ionic-angular/navigation/nav-controller';
import * as import10 from '@angular/core/src/metadata/view';
import * as import11 from '@angular/core/src/linker/component_factory';
import * as import12 from '../../node_modules/ionic-angular/components/toolbar/toolbar.ngfactory';
import * as import13 from '../../node_modules/ionic-angular/components/navbar/navbar.ngfactory';
import * as import14 from '../../node_modules/ionic-angular/components/toolbar/toolbar-item.ngfactory';
import * as import15 from '@angular/core/src/linker/query_list';
import * as import16 from '../../node_modules/ionic-angular/components/button/button.ngfactory';
import * as import17 from '../../node_modules/ionic-angular/components/menu/menu-toggle.ngfactory';
import * as import18 from '../../node_modules/ionic-angular/components/icon/icon.ngfactory';
import * as import19 from '../../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import20 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import21 from '../../node_modules/@angular/common/src/directives/ng_class.ngfactory';
import * as import22 from '../../node_modules/ionic-angular/components/item/item.ngfactory';
import * as import23 from '../../node_modules/ionic-angular/components/avatar/avatar.ngfactory';
import * as import24 from 'ionic-angular/config/config';
import * as import25 from '@angular/core/src/linker/element_ref';
import * as import26 from 'ionic-angular/navigation/view-controller';
import * as import27 from 'ionic-angular/components/app/app';
import * as import28 from 'ionic-angular/components/toolbar/toolbar';
import * as import29 from 'ionic-angular/components/menu/menu-controller';
import * as import30 from 'ionic-angular/util/keyboard';
import * as import31 from '@angular/core/src/zone/ng_zone';
import * as import32 from 'ionic-angular/components/tabs/tabs';
import * as import33 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import34 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import35 from 'ionic-angular/util/form';
import * as import36 from 'ionic-angular/components/item/item-reorder';
import * as import37 from 'ionic-angular/components/icon/icon';
import * as import38 from 'ionic-angular/components/button/button';
import * as import39 from 'ionic-angular/components/menu/menu-toggle';
import * as import40 from 'ionic-angular/components/toolbar/toolbar-item';
import * as import41 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import42 from 'ionic-angular/components/navbar/navbar';
import * as import43 from '@angular/common/src/directives/ng_class';
import * as import44 from 'ionic-angular/components/avatar/avatar';
import * as import45 from 'ionic-angular/components/item/item';
import * as import46 from 'ionic-angular/components/content/content';
import * as import47 from '@angular/core/src/security';
export class Wrapper_Account {
  context:import0.Account;
  changed:boolean;
  constructor(p0:any,p1:any) {
    this.changed = false;
    this.context = new import0.Account(p0,p1);
  }
  detectChangesInternal(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
}
var renderType_Account_Host:import2.RenderComponentType = (null as any);
class _View_Account_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _OnymosServices_0_4:import4.OnymosServices;
  _Account_0_5:Wrapper_Account;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import3.AppElement) {
    super(_View_Account_Host0,renderType_Account_Host,import7.ViewType.HOST,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.selectOrCreateHostElement('page-account',rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_Account0(this.viewUtils,this.injector(0),this._appEl_0);
    this._OnymosServices_0_4 = new import4.OnymosServices();
    this._Account_0_5 = new Wrapper_Account(this.parentInjector.get(import9.NavController),this._OnymosServices_0_4);
    this._appEl_0.initComponent(this._Account_0_5.context,([] as any[]),compView_0);
    compView_0.create(this._Account_0_5.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import4.OnymosServices) && (0 === requestNodeIndex))) { return this._OnymosServices_0_4; }
    if (((token === import0.Account) && (0 === requestNodeIndex))) { return this._Account_0_5.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._Account_0_5.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_Account_Host0(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_Account_Host === (null as any))) { (renderType_Account_Host = viewUtils.createRenderComponentType('',0,import10.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_Account_Host0(viewUtils,parentInjector,declarationEl);
}
export const AccountNgFactory:import11.ComponentFactory<import0.Account> = new import11.ComponentFactory<import0.Account>('page-account',viewFactory_Account_Host0,import0.Account);
const styles_Account:any[] = ([] as any[]);
var renderType_Account:import2.RenderComponentType = (null as any);
class _View_Account0 extends import1.AppView<import0.Account> {
  _el_0:any;
  _Header_0_3:import12.Wrapper_Header;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import3.AppElement;
  _Navbar_2_4:import13.Wrapper_Navbar;
  _text_3:any;
  _el_4:any;
  _ToolbarItem_4_3:import14.Wrapper_ToolbarItem;
  _query_Button_4_0:import15.QueryList<any>;
  _text_5:any;
  _el_6:any;
  /*private*/ _appEl_6:import3.AppElement;
  _Button_6_4:import16.Wrapper_Button;
  _MenuToggle_6_5:import17.Wrapper_MenuToggle;
  _ToolbarItem_6_6:import14.Wrapper_ToolbarItem;
  _query_Button_6_0:import15.QueryList<any>;
  _text_7:any;
  _el_8:any;
  _Icon_8_3:import18.Wrapper_Icon;
  _text_9:any;
  _text_10:any;
  _text_11:any;
  _el_12:any;
  /*private*/ _appEl_12:import3.AppElement;
  _ToolbarTitle_12_4:import19.Wrapper_ToolbarTitle;
  _text_13:any;
  _text_14:any;
  _text_15:any;
  _text_16:any;
  _el_17:any;
  /*private*/ _appEl_17:import3.AppElement;
  _Content_17_4:import20.Wrapper_Content;
  _text_18:any;
  _el_19:any;
  _NgClass_19_3:import21.Wrapper_NgClass;
  _text_20:any;
  _text_21:any;
  _el_22:any;
  /*private*/ _appEl_22:import3.AppElement;
  _Item_22_4:import22.Wrapper_Item;
  _ItemContent_22_5:import22.Wrapper_ItemContent;
  _query_Label_22_0:import15.QueryList<any>;
  _query_Button_22_1:import15.QueryList<any>;
  _query_Icon_22_2:import15.QueryList<any>;
  _text_23:any;
  _el_24:any;
  _Avatar_24_3:import23.Wrapper_Avatar;
  _text_25:any;
  _el_26:any;
  _text_27:any;
  _text_28:any;
  _el_29:any;
  _text_30:any;
  _text_31:any;
  _el_32:any;
  _text_33:any;
  _el_34:any;
  _text_35:any;
  _text_36:any;
  _text_37:any;
  _el_38:any;
  _text_39:any;
  _el_40:any;
  /*private*/ _appEl_40:import3.AppElement;
  _Button_40_4:import16.Wrapper_Button;
  _text_41:any;
  _text_42:any;
  _text_43:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  _map_0:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_13:any;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import3.AppElement) {
    super(_View_Account0,renderType_Account,import7.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this._Header_0_3 = new import12.Wrapper_Header(this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_0),this.renderer,this.parentInjector.get(import26.ViewController,(null as any)));
    this._text_1 = this.renderer.createText(this._el_0,'\n	',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-navbar',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','toolbar');
    this._appEl_2 = new import3.AppElement(2,0,this,this._el_2);
    var compView_2:any = import13.viewFactory_Navbar0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Navbar_2_4 = new import13.Wrapper_Navbar(this.parentInjector.get(import27.App),this.parentInjector.get(import26.ViewController,(null as any)),this.parentInjector.get(import9.NavController,(null as any)),this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_2),this.renderer);
    this._appEl_2.initComponent(this._Navbar_2_4.context,([] as any[]),compView_2);
    this._text_3 = this.renderer.createText((null as any),'\n		',(null as any));
    this._el_4 = this.renderer.createElement((null as any),'ion-buttons',(null as any));
    this.renderer.setElementAttribute(this._el_4,'start','');
    this._ToolbarItem_4_3 = new import14.Wrapper_ToolbarItem(this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_4),this.renderer,this.parentInjector.get(import28.Toolbar,(null as any)),this._Navbar_2_4.context);
    this._query_Button_4_0 = new import15.QueryList<any>();
    this._text_5 = this.renderer.createText(this._el_4,'\n			',(null as any));
    this._el_6 = this.renderer.createElement(this._el_4,'button',(null as any));
    this.renderer.setElementAttribute(this._el_6,'ion-button','');
    this.renderer.setElementAttribute(this._el_6,'menuToggle','');
    this._appEl_6 = new import3.AppElement(6,4,this,this._el_6);
    var compView_6:any = import16.viewFactory_Button0(this.viewUtils,this.injector(6),this._appEl_6);
    this._Button_6_4 = new import16.Wrapper_Button('','',this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_6),this.renderer);
    this._MenuToggle_6_5 = new import17.Wrapper_MenuToggle(this.parentInjector.get(import29.MenuController),new import25.ElementRef(this._el_6),this.parentInjector.get(import26.ViewController,(null as any)),this._Navbar_2_4.context);
    this._ToolbarItem_6_6 = new import14.Wrapper_ToolbarItem(this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_6),this.renderer,this.parentInjector.get(import28.Toolbar,(null as any)),this._Navbar_2_4.context);
    this._query_Button_6_0 = new import15.QueryList<any>();
    this._appEl_6.initComponent(this._Button_6_4.context,([] as any[]),compView_6);
    this._text_7 = this.renderer.createText((null as any),'\n				',(null as any));
    this._el_8 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_8,'name','menu');
    this.renderer.setElementAttribute(this._el_8,'role','img');
    this._Icon_8_3 = new import18.Wrapper_Icon(this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_8),this.renderer);
    this._text_9 = this.renderer.createText((null as any),'\n			',(null as any));
      compView_6.create(this._Button_6_4.context,[([] as any[]).concat([
        this._text_7,
        this._el_8,
        this._text_9
      ]
    )],(null as any));
    this._text_10 = this.renderer.createText(this._el_4,'\n		',(null as any));
    this._text_11 = this.renderer.createText((null as any),'\n		',(null as any));
    this._el_12 = this.renderer.createElement((null as any),'ion-title',(null as any));
    this._appEl_12 = new import3.AppElement(12,2,this,this._el_12);
    var compView_12:any = import19.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(12),this._appEl_12);
    this._ToolbarTitle_12_4 = new import19.Wrapper_ToolbarTitle(this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_12),this.renderer,this.parentInjector.get(import28.Toolbar,(null as any)),this._Navbar_2_4.context);
    this._appEl_12.initComponent(this._ToolbarTitle_12_4.context,([] as any[]),compView_12);
    this._text_13 = this.renderer.createText((null as any),'Account',(null as any));
    compView_12.create(this._ToolbarTitle_12_4.context,[([] as any[]).concat([this._text_13])],(null as any));
    this._text_14 = this.renderer.createText((null as any),'\n	',(null as any));
    compView_2.create(this._Navbar_2_4.context,[
      ([] as any[]),
      ([] as any[]).concat([this._el_4]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_3,
        this._text_11,
        this._el_12,
        this._text_14
      ]
      )
    ]
    ,(null as any));
    this._text_15 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_16 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_17 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this._appEl_17 = new import3.AppElement(17,(null as any),this,this._el_17);
    var compView_17:any = import20.viewFactory_Content0(this.viewUtils,this.injector(17),this._appEl_17);
    this._Content_17_4 = new import20.Wrapper_Content(this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_17),this.renderer,this.parentInjector.get(import27.App),this.parentInjector.get(import30.Keyboard),this.parentInjector.get(import31.NgZone),this.parentInjector.get(import26.ViewController,(null as any)),this.parentInjector.get(import32.Tabs,(null as any)));
    this._appEl_17.initComponent(this._Content_17_4.context,([] as any[]),compView_17);
    this._text_18 = this.renderer.createText((null as any),'\n\n	',(null as any));
    this._el_19 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_19,'class','error-banner');
    this._NgClass_19_3 = new import21.Wrapper_NgClass(this.parentInjector.get(import33.IterableDiffers),this.parentInjector.get(import34.KeyValueDiffers),new import25.ElementRef(this._el_19),this.renderer);
    this._text_20 = this.renderer.createText(this._el_19,'',(null as any));
    this._text_21 = this.renderer.createText((null as any),'\n\n	',(null as any));
    this._el_22 = this.renderer.createElement((null as any),'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_22,'class','item item-block');
    this.renderer.setElementAttribute(this._el_22,'no-lines','');
    this._appEl_22 = new import3.AppElement(22,17,this,this._el_22);
    var compView_22:any = import22.viewFactory_Item0(this.viewUtils,this.injector(22),this._appEl_22);
    this._Item_22_4 = new import22.Wrapper_Item(this.parentInjector.get(import35.Form),this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_22),this.renderer,this.parentInjector.get(import36.ItemReorder,(null as any)));
    this._ItemContent_22_5 = new import22.Wrapper_ItemContent();
    this._query_Label_22_0 = new import15.QueryList<any>();
    this._query_Button_22_1 = new import15.QueryList<any>();
    this._query_Icon_22_2 = new import15.QueryList<any>();
    this._appEl_22.initComponent(this._Item_22_4.context,([] as any[]),compView_22);
    this._text_23 = this.renderer.createText((null as any),'\n		',(null as any));
    this._el_24 = this.renderer.createElement((null as any),'ion-avatar',(null as any));
    this.renderer.setElementAttribute(this._el_24,'item-left','');
    this._Avatar_24_3 = new import23.Wrapper_Avatar();
    this._text_25 = this.renderer.createText(this._el_24,'\n			',(null as any));
    this._el_26 = this.renderer.createElement(this._el_24,'img',(null as any));
    this._text_27 = this.renderer.createText(this._el_24,'\n		',(null as any));
    this._text_28 = this.renderer.createText((null as any),'\n		',(null as any));
    this._el_29 = this.renderer.createElement((null as any),'h2',(null as any));
    this._text_30 = this.renderer.createText(this._el_29,'',(null as any));
    this._text_31 = this.renderer.createText((null as any),'\n		',(null as any));
    this._el_32 = this.renderer.createElement((null as any),'p',(null as any));
    this._text_33 = this.renderer.createText(this._el_32,'Logged in with • ',(null as any));
    this._el_34 = this.renderer.createElement(this._el_32,'B',(null as any));
    this._text_35 = this.renderer.createText(this._el_34,'',(null as any));
    this._text_36 = this.renderer.createText((null as any),'\n	',(null as any));
    this._query_Label_22_0.reset(([] as any[]));
    this._Item_22_4.context.contentLabel = this._query_Label_22_0.first;
    compView_22.create(this._Item_22_4.context,[
      ([] as any[]).concat([this._el_24]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_23,
        this._text_28,
        this._el_29,
        this._text_31,
        this._el_32,
        this._text_36
      ]
      ),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_37 = this.renderer.createText((null as any),'\n\n	',(null as any));
    this._el_38 = this.renderer.createElement((null as any),'p',(null as any));
    this.renderer.setElementAttribute(this._el_38,'class','logout-button-spacing');
    this._text_39 = this.renderer.createText(this._el_38,'\n		',(null as any));
    this._el_40 = this.renderer.createElement(this._el_38,'button',(null as any));
    this.renderer.setElementAttribute(this._el_40,'block','');
    this.renderer.setElementAttribute(this._el_40,'color','danger');
    this.renderer.setElementAttribute(this._el_40,'ion-button','');
    this._appEl_40 = new import3.AppElement(40,38,this,this._el_40);
    var compView_40:any = import16.viewFactory_Button0(this.viewUtils,this.injector(40),this._appEl_40);
    this._Button_40_4 = new import16.Wrapper_Button((null as any),'',this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_40),this.renderer);
    this._appEl_40.initComponent(this._Button_40_4.context,([] as any[]),compView_40);
    this._text_41 = this.renderer.createText((null as any),'\n			Logout\n		',(null as any));
    compView_40.create(this._Button_40_4.context,[([] as any[]).concat([this._text_41])],(null as any));
    this._text_42 = this.renderer.createText(this._el_38,'\n	',(null as any));
    this._text_43 = this.renderer.createText((null as any),'\n\n',(null as any));
    compView_17.create(this._Content_17_4.context,[
      ([] as any[]),
      ([] as any[]).concat([
        this._text_18,
        this._el_19,
        this._text_21,
        this._el_22,
        this._text_37,
        this._el_38,
        this._text_43
      ]
      ),
      ([] as any[])
    ]
    ,(null as any));
    this._expr_0 = import8.UNINITIALIZED;
    this._expr_1 = import8.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_6,'click',this.eventHandler(this._handle_click_6_0.bind(this)));
    this._expr_4 = import8.UNINITIALIZED;
    this._expr_6 = import8.UNINITIALIZED;
    this._expr_7 = import8.UNINITIALIZED;
    this._map_0 = import5.pureProxy1((p0:any):{[key: string]:any} => {
      return {'error-banner-show': p0};
    });
    this._expr_10 = import8.UNINITIALIZED;
    this._expr_11 = import8.UNINITIALIZED;
    this._expr_12 = import8.UNINITIALIZED;
    this._expr_13 = import8.UNINITIALIZED;
    var disposable_1:Function = this.renderer.listen(this._el_40,'click',this.eventHandler(this._handle_click_40_0.bind(this)));
    this.init(([] as any[]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._text_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._text_14,
      this._text_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._text_28,
      this._el_29,
      this._text_30,
      this._text_31,
      this._el_32,
      this._text_33,
      this._el_34,
      this._text_35,
      this._text_36,
      this._text_37,
      this._el_38,
      this._text_39,
      this._el_40,
      this._text_41,
      this._text_42,
      this._text_43
    ]
    ,[
      disposable_0,
      disposable_1
    ]
    ,([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import37.Icon) && (8 === requestNodeIndex))) { return this._Icon_8_3.context; }
    if (((token === import38.Button) && ((6 <= requestNodeIndex) && (requestNodeIndex <= 9)))) { return this._Button_6_4.context; }
    if (((token === import39.MenuToggle) && ((6 <= requestNodeIndex) && (requestNodeIndex <= 9)))) { return this._MenuToggle_6_5.context; }
    if (((token === import40.ToolbarItem) && ((6 <= requestNodeIndex) && (requestNodeIndex <= 9)))) { return this._ToolbarItem_6_6.context; }
    if (((token === import40.ToolbarItem) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 10)))) { return this._ToolbarItem_4_3.context; }
    if (((token === import41.ToolbarTitle) && ((12 <= requestNodeIndex) && (requestNodeIndex <= 13)))) { return this._ToolbarTitle_12_4.context; }
    if (((token === import42.Navbar) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 14)))) { return this._Navbar_2_4.context; }
    if (((token === import28.Header) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 15)))) { return this._Header_0_3.context; }
    if (((token === import43.NgClass) && ((19 <= requestNodeIndex) && (requestNodeIndex <= 20)))) { return this._NgClass_19_3.context; }
    if (((token === import44.Avatar) && ((24 <= requestNodeIndex) && (requestNodeIndex <= 27)))) { return this._Avatar_24_3.context; }
    if (((token === import45.Item) && ((22 <= requestNodeIndex) && (requestNodeIndex <= 36)))) { return this._Item_22_4.context; }
    if (((token === import45.ItemContent) && ((22 <= requestNodeIndex) && (requestNodeIndex <= 36)))) { return this._ItemContent_22_5.context; }
    if (((token === import38.Button) && ((40 <= requestNodeIndex) && (requestNodeIndex <= 41)))) { return this._Button_40_4.context; }
    if (((token === import46.Content) && ((17 <= requestNodeIndex) && (requestNodeIndex <= 43)))) { return this._Content_17_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._Header_0_3.detectChangesInternal(this,this._el_0,throwOnChange);
    this._Navbar_2_4.detectChangesInternal(this,this._el_2,throwOnChange);
    this._ToolbarItem_4_3.detectChangesInternal(this,this._el_4,throwOnChange);
    if (this._Button_6_4.detectChangesInternal(this,this._el_6,throwOnChange)) { this._appEl_6.componentView.markAsCheckOnce(); }
    const currVal_3:any = '';
    this._MenuToggle_6_5.check_menuToggle(currVal_3,throwOnChange,false);
    this._MenuToggle_6_5.detectChangesInternal(this,this._el_6,throwOnChange);
    this._ToolbarItem_6_6.detectChangesInternal(this,this._el_6,throwOnChange);
    const currVal_5:any = 'menu';
    this._Icon_8_3.check_name(currVal_5,throwOnChange,false);
    this._Icon_8_3.detectChangesInternal(this,this._el_8,throwOnChange);
    if (this._ToolbarTitle_12_4.detectChangesInternal(this,this._el_12,throwOnChange)) { this._appEl_12.componentView.markAsCheckOnce(); }
    if (this._Content_17_4.detectChangesInternal(this,this._el_17,throwOnChange)) { this._appEl_17.componentView.markAsCheckOnce(); }
    const currVal_8:any = 'error-banner';
    this._NgClass_19_3.check_klass(currVal_8,throwOnChange,false);
    const currVal_9:any = this._map_0((this.context.errorMessage !== ''));
    this._NgClass_19_3.check_ngClass(currVal_9,throwOnChange,false);
    this._NgClass_19_3.detectChangesInternal(this,this._el_19,throwOnChange);
    if (this._Item_22_4.detectChangesInternal(this,this._el_22,throwOnChange)) { this._appEl_22.componentView.markAsCheckOnce(); }
    this._ItemContent_22_5.detectChangesInternal(this,this._el_22,throwOnChange);
    this._Avatar_24_3.detectChangesInternal(this,this._el_24,throwOnChange);
    const currVal_15:any = '';
    this._Button_40_4.check_block(currVal_15,throwOnChange,false);
    const currVal_16:any = 'danger';
    this._Button_40_4.check_color(currVal_16,throwOnChange,false);
    if (this._Button_40_4.detectChangesInternal(this,this._el_40,throwOnChange)) { this._appEl_40.componentView.markAsCheckOnce(); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_6_0.dirty) {
        this._query_Button_6_0.reset([this._Button_6_4.context]);
        this._ToolbarItem_6_6.context._buttons = this._query_Button_6_0;
        this._query_Button_6_0.notifyOnChanges();
      }
      if (this._query_Button_4_0.dirty) {
        this._query_Button_4_0.reset([this._Button_6_4.context]);
        this._ToolbarItem_4_3.context._buttons = this._query_Button_4_0;
        this._query_Button_4_0.notifyOnChanges();
      }
      if (this._query_Button_22_1.dirty) {
        this._query_Button_22_1.reset(([] as any[]));
        this._Item_22_4.context._buttons = this._query_Button_22_1;
        this._query_Button_22_1.notifyOnChanges();
      }
      if (this._query_Icon_22_2.dirty) {
        this._query_Icon_22_2.reset(([] as any[]));
        this._Item_22_4.context._icons = this._query_Icon_22_2;
        this._query_Icon_22_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Button_6_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_22_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_40_4.context.ngAfterContentInit(); }
    }
    const currVal_0:any = this._Navbar_2_4.context._hidden;
    if (import5.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_2,'hidden',currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = this._Navbar_2_4.context._sbPadding;
    if (import5.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementClass(this._el_2,'statusbar-padding',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_4:any = this._MenuToggle_6_5.context.isHidden;
    if (import5.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementProperty(this._el_6,'hidden',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_6:any = this._Icon_8_3.context._hidden;
    if (import5.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementClass(this._el_8,'hide',currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = this._Content_17_4.context._sbPadding;
    if (import5.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_17,'statusbar-padding',currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_10:any = import5.interpolate(1,'\n		',this.context.errorMessage,'\n	');
    if (import5.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this.renderer.setText(this._text_20,currVal_10);
      this._expr_10 = currVal_10;
    }
    const currVal_11:any = this.context.userPhoto;
    if (import5.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this.renderer.setElementProperty(this._el_26,'src',this.viewUtils.sanitizer.sanitize(import47.SecurityContext.URL,currVal_11));
      this._expr_11 = currVal_11;
    }
    const currVal_12:any = import5.interpolate(1,'',this.context.userName,'');
    if (import5.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this.renderer.setText(this._text_30,currVal_12);
      this._expr_12 = currVal_12;
    }
    const currVal_13:any = import5.interpolate(1,'',this.context.authProvider,'');
    if (import5.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this.renderer.setText(this._text_35,currVal_13);
      this._expr_13 = currVal_13;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Navbar_2_4.context.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._Icon_8_3.context.ngOnDestroy();
    this._Content_17_4.context.ngOnDestroy();
  }
  private _handle_click_6_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._MenuToggle_6_5.context.toggle()) !== false);
    return (true && pd_0);
  }
  private _handle_click_40_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.socialLogout()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_Account0(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import3.AppElement):import1.AppView<import0.Account> {
  if ((renderType_Account === (null as any))) { (renderType_Account = viewUtils.createRenderComponentType('',0,import10.ViewEncapsulation.None,styles_Account,{})); }
  return new _View_Account0(viewUtils,parentInjector,declarationEl);
}