/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from './auto-resize';
import * as import1 from '@angular/core/src/linker/view';
export class Wrapper_AutoResize {
  context:import0.AutoResize;
  changed:boolean;
  constructor(p0:any) {
    this.changed = false;
    this.context = new import0.AutoResize(p0);
  }
  detectChangesInternal(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
}